### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by prada-hvh** [SunOner/yolov8_aimbot#10]
To change capture parameters you can manually delete the old object using `del obj`.
[ERROR:0@5.407] global obsensor_uvc_stream_channel.cpp:156 cv::obsensor::getStreamChannelGroup Camera index out of range
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.
WARNING  'source' is missing. Using 'source=C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\assets'.

**Comment by SunOner** [comment]
Change camera id

**Comment by prada-hvh** [comment]
> Change camera id

which one?
