### ISSUE TITLE
Aim not working detection still works

### ISSUE THREAD

**Issue by JasonRose95** [SunOner/yolov8_aimbot#100]
When running the run.py everything works with no error code. The mouse will move to the top left corner of the screen and stay there. The debug window will show the body and the head and is detecting it fine but the mouse will not move to it. I'm not sure what is causing the issue. I have multiple monitors but it looks like it is detecting the primary one which I am running the game on.

**Comment by JasonRose95** [comment]
W_x, W_y, v_x, v_y in mouse.py are returning negative values i think this is causing my mouse to go to 0,0

**Comment by cats-ui** [comment]
Try to update now
