### ISSUE TITLE
Закрывается cmd сразу после запуска

### ISSUE THREAD

**Issue by Loleef** [SunOner/yolov8_aimbot#104]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153488744/6aa7927c-663c-4a4c-94f0-7c5cc5585caf)

**Comment by IdyNaLan** [comment]
Пропиши pip install pyserial

**Comment by Weser87** [comment]
Обновите код, баг пофикшен

**Comment by SunOner** [comment]
pip install -r requirements.txt
