### ISSUE TITLE
help

### ISSUE THREAD

**Issue by prada-hvh** [SunOner/yolov8_aimbot#11]
https://youtu.be/u_Po2l3DBWY

**Comment by prada-hvh** [comment]
# Your screen resolution
original_screen_width = 1920
original_screen_height = 1080

# Object Search window resolution
screen_width = 1920
screen_height = 1080

# dxcam Capture method
Dxcam_capture = True
dxcam_capture_fps = 60 # More value, more mouse swing
dxcam_monitor_id = 0
dxcam_gpu_id = 0
dxcam_max_buffer_len = 64

# Obs capture method
Obs_capture = True
Obs_camera_id = 0

# Windows capture method
Windows_capture = False

# Aim settings
head_correction = True
body_y_offset = 0.37
head_y_offset = 0.37

# Mouse settings 
mouse_smoothing = 0.4 # 1 is default
mouse_auto_shoot = True
mouse_auto_shoot_timer = False
mouse_auto_shoot_sleep_time = 0.2
mouse_auto_aim =  True

# Cv2 debug window settings
show_window = False
show_speed = False
show_fps = False
debug_window_scale_percent = 100
debug_window_name = 'RT'

# AI settings
model_path='models/sunxds_0.2.pt'

def Calculate_screen_offset():
    left = original_screen_width / 2 - screen_width / 2
    top = original_screen_height / 2 - screen_height / 2
    width = left + screen_width
    height = top + screen_height
    return (int(left), int(top), int(width), int(height))

players = []
heads = []

**Comment by SunOner** [comment]
Obs_capture = False
dxcam_capture_fps = 30
mouse_smoothing = 1

**Comment by SunOner** [comment]
> reuslt: Engine error

Read [How to export model to .engine](https://github.com/SunOner/yolov8_aimbot#export-pt-model-to-engine)

> pt : 15-25 fps
> onnx: 2 fps

Reduce the target search window, you are heavily loading the system trying to search for targets in a resolution of 1920x1080, try a resolution of 480x300.
