### ISSUE TITLE
OBS capture 

### ISSUE THREAD

**Issue by Hiradpi** [SunOner/yolov8_aimbot#111]
when the obs capture is selected it takes full screen and does not cut it like dx cam and windows capture does 
that causes the ai to try and scan the whole screen and it cannot detect it

**Comment by Hiradpi** [comment]
I tried to use crop effects in the obs it self but it was very faulty the mouse was jumping (I put the fps limit to 30 just like dxcam)

**Comment by cats-ui** [comment]
cut it in obs

**Comment by SunOner** [comment]
Stretch the image in the preview window and press CTRL+D, this centers the image.

**Comment by max1090** [comment]
> 我在 valorant 中测试了所有这些

Does it works？
