### ISSUE TITLE
В чем проблема?

### ISSUE THREAD

**Issue by GuessWH0oo** [SunOner/yolov8_aimbot#118]
![изображение_2023-12-16_142247393](https://github.com/SunOner/yolov8_aimbot/assets/153991487/c2af6faf-f98b-4ee0-a21d-1ad4ab61eaa6)
Короче пытался сначала модельки из pt в engine - не получилось
Потому делаю pip uninstall onnx, потом заново прописываю pt в engine и вот что на выходе

**Comment by GuessWH0oo** [comment]
А потом вот
![изображение_2023-12-16_142852354](https://github.com/SunOner/yolov8_aimbot/assets/153991487/98a0dfd6-b809-41dc-8877-7bb7a145854c)
Что не так сделал с модельками? Что исправить чтоб загрузилось

**Comment by SunOner** [comment]
Он экспортируется.

**Comment by GuessWH0oo** [comment]
> Он экспортируется.

![изображение_2023-12-16_152709851](https://github.com/SunOner/yolov8_aimbot/assets/153991487/79cf45ce-b000-41cd-905e-8955b7b7d82f)
