### ISSUE TITLE
Как исправить? Не экспортируется

### ISSUE THREAD

**Issue by Kurban055** [SunOner/yolov8_aimbot#119]
![изображение_2023-12-16_151154002](https://github.com/SunOner/yolov8_aimbot/assets/153992780/ca98ffea-821b-43a2-8150-bbd3d9c08799)

**Comment by Kurban055** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153992780/4ec4c2d5-c823-46df-9ea1-97fd87850523)

**Comment by GuessWH0oo** [comment]
Как починил? У меня тоже самое, висит этот эскпорт бесконечно. Час с лишним прождал, ничего...
