### ISSUE TITLE
 After this new update I'm getting cuda error but I already have cuda installed

### ISSUE THREAD

**Issue by Allmight0000** [SunOner/yolov8_aimbot#12]
C:\Users\Administrator\Desktop\yolov8_aimbot-main\yolov8_aimbot-main>pip list | findstr cuda
cupy-cuda12x             12.2.0
pycuda                   2022.2.2

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\Administrator\Desktop\yolov8_aimbot-main\yolov8_aimbot-main>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

C:\Users\Administrator\Desktop\yolov8_aimbot-main\yolov8_aimbot-main>C:\Users\Administrator\Desktop\yolov8_aimbot-main\yolov8_aimbot-main\main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\yolov8_aimbot-main\yolov8_aimbot-main\main.py", line 7, in <module>
    from targets import *
  File "C:\Users\Administrator\Desktop\yolov8_aimbot-main\yolov8_aimbot-main\targets.py", line 3, in <module>
    from main import screen_x_center, screen_y_center
  File "C:\Users\Administrator\Desktop\yolov8_aimbot-main\yolov8_aimbot-main\main.py", line 12, in <module>
    from cuda import cuda, cudart
ModuleNotFoundError: No module named 'cuda'

**Comment by SunOner** [comment]
Updated
