### ISSUE TITLE
win32ui.error: CreateCompatibleDC failed

### ISSUE THREAD

**Issue by GuessWH0oo** [SunOner/yolov8_aimbot#120]
Что сделать? Подобное где-то видел в Issues, но не нашел решения
![изображение_2023-12-16_153917689](https://github.com/SunOner/yolov8_aimbot/assets/153991487/ad165140-a5d0-4c83-96c3-840779920fde)
Переустанавливать torch пробовал, не помогло

**Comment by GuessWH0oo** [comment]
Короче не могу разобраться, pt моментально всё грузит и тд. Переделываешь в engine идёт вченый экспорт и всё
![изображение_2023-12-16_185700310](https://github.com/SunOner/yolov8_aimbot/assets/153991487/0047579f-a1af-433d-96d3-b666d9128e6c)
Скачал с бусти новые модели  и лучше же в engine играть... А оно никак, что поделать можно? Целый день сегодня убил, пытаюсь - всё никак

**Comment by SunOner** [comment]
[Readme.md export pt model to engine](https://github.com/SunOner/yolov8_aimbot?tab=readme-ov-file#export-pt-model-to-engine)
verbose=True 👀

**Comment by GuessWH0oo** [comment]
![изображение_2023-12-16_200129168](https://github.com/SunOner/yolov8_aimbot/assets/153991487/f67b3636-a8f3-4c49-8572-271d314491cc)
Там куча всего , что там должно было быть :D

**Comment by SunOner** [comment]
Так и должно быть, а что ты хотел там увидеть? хД

**Comment by SunOner** [comment]
show_window = on поставь
