### ISSUE TITLE
 и загрузите скрипт на ардуино. (кнопка стрелочка в право).

### ISSUE THREAD

**Issue by Jolenkov123** [SunOner/yolov8_aimbot#121]
Iopta поцы, где скрипт взять этот ? Туплю

**Comment by SunOner** [comment]
1Arduino.ino

**Comment by Jolenkov123** [comment]
А потом запускать как положенно ?

**Comment by SunOner** [comment]
Загрузил скрипт на ардуино?

**Comment by Jolenkov123** [comment]
да

**Comment by SunOner** [comment]
Распиши все действия которые ты выполняешь.

**Comment by Jolenkov123** [comment]
Загрузил скрипт, открываю cmd запускаю py, адруино обнаружено, подключаю мышку к usb, мышка не подключается

**Comment by SunOner** [comment]
После того как ты подключаешь мышку к usb host shield'а она должна начать работать даже без запущенного скрипта run.py.

**Comment by Jolenkov123** [comment]
Паять контакты не надо никакие ? Так должно работать же ?

**Comment by SunOner** [comment]
Если мышка потребляет много, (aka bloody) паяй эти контакты.
![2023-12-18_18-44-52](https://github.com/SunOner/yolov8_aimbot/assets/44489132/e69fc4a8-a644-4101-bab4-98d4b93fead8)

**Comment by Jolenkov123** [comment]
Вместе их спаять получается ?

**Comment by Jolenkov123** [comment]
Извиняюсь бля, они уже замучены у меня

**Comment by Jolenkov123** [comment]
Ладно завтра отпишусь

**Comment by Jolenkov123** [comment]
Получается все подключаю и в смд пишу команду  run.py ?

**Comment by Jolenkov123** [comment]
Так, сейчас получается мышка просто вниз убегает и все не поднимается, в стороны водит

**Comment by SunOner** [comment]
Попробуй изменить в hidcustom.h 
`
struct MYMOUSEINFO
{
  uint8_t buttons;
  uint8_t dX;
  uint8_t dY;
  int8_t wheel;
};
`

**Comment by Jolenkov123** [comment]
Мышка теперь двигается, в игре теперь на движениях предметы меняются

**Comment by SunOner** [comment]
Какие предметы?)

**Comment by Jolenkov123** [comment]
Ну смысле, колесико постоянно крутится на мышке  как будто, оружие меняет крч.

**Comment by djizi** [comment]
> В смысле, колесо постоянно крутится на мышке, как будто оружие меняет креч.

И че ты сделал? у меня так же

**Comment by Accentualll** [comment]
Привет. Всё сделал, мышь двигается, НО есть некоторые трудности. В Warface при резком движении мыши она пытается двигаться, но дёргается обратно, какие-то лаги происходят. Пытался менять dpi, частоту опроса, но результатов нет. Как быть? Подписку оформлю обязательно если разберёмся в чем беда.

**Comment by Clowler** [comment]
Такая же фигня, мышка Xtrfy m42 драйвера последние с офф. сайта скачал, загружаю скетч но мышка не двигается вообще, захожу в этот файл hidcustom, меняю местами X на Y и загружаю скетч, мышка опускается вниз, далее uint16 поменял X и Y на 8 по отдельности потом повторил и все равно не работает, то есть вообще не двигается а в мониторе сериал пишет там 0 0 FF 00 00 00 строк 4-5 так пишет и потом одни нули где-то 8 строк, и повторяет. Так же менял dpi и частоту на меньшую, безрезультатно.
