### ISSUE TITLE
 Is there any way to reduce the shaking? Or are you currently already on the best solution?

### ISSUE THREAD

**Issue by Allmight0000** [SunOner/yolov8_aimbot#13]
Is there any way to reduce the shaking? Or are you currently already on the best solution?

How do you capture images to train the model so I can contribute to the project?

**Comment by SunOner** [comment]
> Is there any way to reduce the shaking? Or are you currently already on the best solution?

At the moment, we have solved the problem with shaking by simply limiting fps.

> How do you capture images to train the model so I can contribute to the project?

After a while I will write a lesson on how to train a model.

**Comment by Allmight0000** [comment]
> > Is there any way to reduce the shaking? Or are you currently already on the best solution?
> 
> At the moment, we have solved the problem with shaking by simply limiting fps.
> 
> > How do you capture images to train the model so I can contribute to the project?
> 
> After a while I will write a lesson on how to train a model.


For me it's still shaking a lot, where should I change it to reduce it? I'm using it on bf2042 COD

**Comment by SunOner** [comment]
Try to limit fps. If you use dxcam, set dxcam_capture_fps = 30, or try using Windows_capture.

**Comment by Allmight0000** [comment]
> Tente limitar o fps. Se você usa dxcam, defina dxcam_capture_fps = 30 ou tente usar Windows_capture.


I did what you said but it still keeps shaking a lot. Is there no option to reduce the speed of the movement?
