### ISSUE TITLE
When I ran the onnx model, I received an error message saying "Unexpected input data type"

### ISSUE THREAD

**Issue by ColoGlaze** [SunOner/yolov8_aimbot#135]
When I use the onnx model by modifying the ini file, running "run. py" will prompt an error message of "onnxruntime. cap. onnxruntime. ybind11_state. InvalidArgument: [ONNXRuntimeError]: 2: INVALID-ARGUMENT: Unexpected input data type. Actual: (tensor (float)), expected: (tensor (float16))"
The error message is as follows:
Onnx CPU loaded
Aimbot is started Enjoy!
[RightMouseButton] - Aiming at the target
[F2] - EXIT
[F3] - PAUSE AIM
Loading models \ clusters_ 0.2.1_ 640. onnx for ONNX runtime conference
Traceback (most recent call last):
File "D: \ YOLO \ yolov8_imbot main \ run. py", line 233, in<module>
Init()
File "D: \ Python \ lib \ site packages \ torch \ utils \ contextlib. py", line 115, in decorate_ Context
Return fun (* args, * * kwargs)
File "D: \ YOLO \ yolov8_imbot main \ run. py", line 164, in init
For frame in result:
File "D: \ Python \ lib \ site packages \ torch \ utils \ contextlib. py", line 35, in generator_ Context
Response=gen. send (None)
File "D: \ python \ lib \ site packages \ ultraviolet \ engine \ predictor. py", line 265, in stream_ Inference
Preds=self. reference (im, * args, * * kwargs)
File "D: \ python \ lib \ site packages \ ultrasonic \ engine \ predictor. py", line 137, in conference
Return self. model (im, augment=self. args. augment, visualize=visualize)
File "D: \ python \ lib \ site packages \ torch \ n \ modules \ module. py", line 1518, in_ Wrapped_ Call_ Impl
Return self_ Call_ Impl (* args, * * kwargs)
File "D: \ python \ lib \ site packages \ torch \ n \ modules \ module. py", line 1527, in_ Call_ Impl
Return forward_ Call (* args, * * kwargs)
File "D: \ python \ lib \ site packages \ ultraviolet \ nn \ autobackend. py", line 356, in forward
Y=self. session. run (self. outputtnames, {self. session. get_inputs() [0]. name: im})
File "D: \ Python \ lib \ site packages \ onnxruntime \ capi \ onnxruntime \ reference_collection. py", line 220, in run
Return self_ Sess. run (outputnames, inputfeed, runoptions)
Onnxruntime. cap. onnxruntime_ Pybind11_ State InvalidArgument: [ONNXRuntimeError]: 2: INVALID_ ARGUENT: Unexpected input data type Actual: (tensor (float)), expected: (tensor (float16))
![image](https://github.com/SunOner/yolov8_aimbot/assets/125593179/735d048d-bfe8-42d7-a67f-dbd63e47efcd)

**Comment by ColoGlaze** [comment]
I tried updating the onnxruntime and onnxruntime gpu libraries, but the error message is different from before. Now, after running the file of the onnx model, The error message is "RuntimeError: D: \ a \ _work \ 1 \ \ onnxruntime \ python \ onnxruntime \ ybind_state. cc: 743 onnxruntime:: python:: CreatExecutionProviderInstance CUDA-PATH is set but CUDA was not able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page"（ https://onnxruntime.ai/docs/execution-providers/cuda-executionprovider.html#requirements ）Make sure they're in the PATH, and that your GPU is supported “
The following are all error messages:
Onnx CPU loaded.
Aimbot is started. Enjoy!
[RightMouseButton] - Aiming at the target
[F2] - EXIT
[F3] - PAUSE AIM
An open debug window can affect performance.
Loading models\sunxds_0.2.1_nano_320.onnx for ONNX Runtime inference...
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2 0 2 3 - 1 2 - 2 2   1 4 : 2 6 : 5 8 . 2 8 5 9 4 3 9   [ E : o n n x r u n t i m e : D e f a u l t ,   p r o v i d e r _ b r i d g e _ o r t . c c : 1 4 8 0   o n n x r u n t i m e : : T r y G e t P r o v i d e r I n f o _ C U D A ]   D : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ s e s s i o n \ p r o v i d e r _ b r i d g e _ o r t . c c : 1 1 9 3   o n n x r u n t i m e : : P r o v i d e r L i b r a r y : : G e t   [ O N N X R u n t i m e E r r o r ]   :   1   :   F A I L   :   L o a d L i b r a r y   f a i l e d   w i t h   e r r o r   1 2 6   " "   w h e n   t r y i n g   t o   l o a d   " D : \ p y t h o n \ l i b \ s i t e - p a c k a g e s \ o n n x r u n t i m e \ c a p i \ o n n x r u n t i m e _ p r o v i d e r s _ c u d a . d l l " 
 
 2 0 2 3 - 1 2 - 2 2   1 4 : 2 6 : 5 8 . 3 1 5 2 1 9 7   [ E : o n n x r u n t i m e : D e f a u l t ,   p r o v i d e r _ b r i d g e _ o r t . c c : 1 4 8 0   o n n x r u n t i m e : : T r y G e t P r o v i d e r I n f o _ C U D A ]   D : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ s e s s i o n \ p r o v i d e r _ b r i d g e _ o r t . c c : 1 1 9 3   o n n x r u n t i m e : : P r o v i d e r L i b r a r y : : G e t   [ O N N X R u n t i m e E r r o r ]   :   1   :   F A I L   :   L o a d L i b r a r y   f a i l e d   w i t h   e r r o r   1 2 6   " "   w h e n   t r y i n g   t o   l o a d   " D : \ p y t h o n \ l i b \ s i t e - p a c k a g e s \ o n n x r u n t i m e \ c a p i \ o n n x r u n t i m e _ p r o v i d e r s _ c u d a . d l l " 
 
 Traceback (most recent call last):
  File "D:\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\YOLO\yolov8_aimbot-main\run.py", line 233, in <module>
    init()
  File "D:\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\YOLO\yolov8_aimbot-main\run.py", line 137, in init
    result = model.predict(
  File "D:\python\lib\site-packages\ultralytics\engine\model.py", line 232, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "D:\python\lib\site-packages\ultralytics\engine\predictor.py", line 317, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "D:\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\python\lib\site-packages\ultralytics\nn\autobackend.py", line 159, in __init__
    session = onnxruntime.InferenceSession(w, providers=providers)
  File "D:\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
    raise fallback_error from e
  File "D:\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "D:\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:743 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
![image](https://github.com/SunOner/yolov8_aimbot/assets/125593179/77780b63-4d48-4529-b480-4d36adc121a5)

**Comment by SunOner** [comment]
CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

**Comment by ColoGlaze** [comment]
> CUDA_PATH已设置，但无法加载 CUDA。请按照 GPU 要求页面 （[https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements）](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) 中所述安装正确版本的 CUDA 和 cuDNN，确保它们位于 PATH 中，并且您的 GPU 受支持。

My cuda version is 12.1, does it not support the cuda environment for version 12.1？
