### ISSUE TITLE
Can you post your dataset used for the sunxds_0.2.1.pt model?

### ISSUE THREAD

**Issue by SouljaVR** [SunOner/yolov8_aimbot#14]
If you could post the dataset somewhere that would be great, perhaps huggingface or something. I would like to contribute to the dataset. Thank you for your work!

**Comment by SunOner** [comment]
Hi thanks for the support. I wanted to share the dataset, but I ran into a problem, my dataset contains a lot of personal information. Maybe I'll post it in the future.
