### ISSUE TITLE
Arduino error upload

### ISSUE THREAD

**Issue by IdyNaLan** [SunOner/yolov8_aimbot#141]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153688473/424d5cb7-f72b-4f2c-8992-a59130a80bb8)
Скетч использует 17302 байт (60%) памяти устройства. Всего доступно 28672 байт.
Глобальные переменные используют 509 байт (19%) динамической памяти, оставляя 2051 байт для локальных переменных. Максимум: 2560 байт.
Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

**Comment by SunOner** [comment]
Это не ошибка, скетч загрузился. Просто включен подробный вывод при загрузке на устройство.
