### ISSUE TITLE
Target Detection & Mouse Movement

### ISSUE THREAD

**Issue by Bazz0r** [SunOner/yolov8_aimbot#145]
Hello, since the last update I am finding the mouse movement is struggling to decide on a target to choose from. The mouse is switching between objects that have been detected, it moves from left to right and does not settle on a single oject. If I run a release from around two days ago, this does not happen. Can you advise what may be causing this behaviour? Thank you

**Comment by SunOner** [comment]
I'm working on it,

**Comment by Bazz0r** [comment]
Thank you very much

**Comment by SunOner** [comment]
Code updated.

**Comment by Forward0xperator** [comment]
> Code updated.

works perfect on gtx1080ti surprisingly after finding optimizations. its just too good, thanks man.

**Comment by Bazz0r** [comment]
Hello, thanks for working on this. The issue for me in Call of Duty Warzone persists, this did not happen on a release from a few days ago. I have made a video of the issue for you to see, I hope this helps:

https://drive.google.com/file/d/1JcAsaJofhU0wfcxjJZFqRm_Y0N301d43/view?usp=drive_link

**Comment by SunOner** [comment]
Try increasing the value of mouse_smoothing or mouse_slow_down_factor.

**Comment by Bazz0r** [comment]
Thank you, increasing mouse slow down fixed the issue, really appreciate your help
