### ISSUE TITLE
error runtime

### ISSUE THREAD

**Issue by laaizy** [SunOner/yolov8_aimbot#148]
![cmd_ta6AD4FS4N](https://github.com/SunOner/yolov8_aimbot/assets/155037692/8a0a42ba-6c3a-40fa-9d6a-4a959a0ad3c8)
 
how to fix

**Comment by SunOner** [comment]
copy the full output from the console

**Comment by laaizy** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/155037692/51495831-dac7-4774-ac15-595017789e14)
