### ISSUE TITLE
how use this python code in pubg?

### ISSUE THREAD

**Issue by ShermanGu12** [SunOner/yolov8_aimbot#150]
I found that there are three mouse movement modes, but in pubg, when you shoot, you will find that the crosshair cannot stay on the person.The accurate heart beats very hard and will eventually point upwards towards the person.I enabled the Logitech lua script to counter recoil, but the mouse movement of yolo8 conflicts with the lua script.

Is it possible to add PID mouse movement method to yolo8?

thanks verymuch

**Comment by SunOner** [comment]
OK, I'll add a PID for the mouse soon.
