### ISSUE TITLE
WARNING ⚠️ NMS time limit 0.550s exceeded

### ISSUE THREAD

**Issue by StereoPancake6** [SunOner/yolov8_aimbot#159]
"WARNING ⚠️ NMS time limit 0.550s exceeded" when on RTX 3050 getting this error makes the ai move the cursor once every 1-2 seconds EXTREMELY slow anyone know a fix? (using a model trained on a gtx 1080 ti)

**Comment by StereoPancake6** [comment]
heres some more info: model is put onto RTX 3050 pc (after being trained on gtx 1080ti) and then it is turned from .pt to .engine and then ran.

**Comment by StereoPancake6** [comment]
I've also done every fix recommended, could I have some dependencies missing? improperly installed cuda? ect?

**Comment by SunOner** [comment]
write the command you used to export and train the model

**Comment by StereoPancake6** [comment]
Training: yolo task=detect mode=train imgsz=640 data=CustomCharacterPath.yaml epochs=1000 batch=16 name=Rust

Export: yolo export model="models/rust.pt" format=engine half=true device=0 imgsz=448

**Comment by StereoPancake6** [comment]
heres a little more info, it works fine on my system but once i send it to my friend he has the NMS Issue.

The system it works on:
CPU: ryzen 5 5600x
GPU: GTX 1080 Ti 

The system theres an issue on:
CPU: ryzen 3 3200g
GPU:  RTX 3050

could it be trying to use the ryzen 3 3200g's integrated graphics instead of using the rtx 3050? if so how can i change it?

**Comment by Geist4587** [comment]
Please please watch my videos I don't want any followers I need the help of the masses Bungie the Destiny 2 developers have been hacking my HP Omen PC for over a year I've asked for help everywhere Facebook Instagram YouTube and Twitter put me in incognito so the truth  It doesn't come out, the sad thing is I haven't even paid it off completely and they don't stop hacking me, please distribute my videos, help me, I've been fighting Bungie for a long time with depression.  https://youtube.com/shorts/feRDkmBOyA4?si=GoWKFnyxqIi-eWkg
