### ISSUE TITLE
cannot install tensorrt

### ISSUE THREAD

**Issue by Gemini899** [SunOner/yolov8_aimbot#16]
i am using your aimbot and it work really well, i made a train for rust and it works pretty damn well but sadly I can only use the .pt version since i cannot run the engine because i can't install tensorrt.
i tried everything i have python 3.11.5.
if i run the command i get the error: ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: 'C:\\Users\\PC\\tensorrt-*-cp311-none-win_amd64.whl'

 no clue what to do :(

**Comment by Gemini899** [comment]
i have a rtx 3090 and i only get about 30 fps in game hope to improve the performance with tensorrt

**Comment by SunOner** [comment]
Check first whether the versions of python, tensorrt, cuda, cudnn converge.
Next, double-check item 4 in the [documentation](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-861/install-guide/index.html#installing-zip)

**Comment by Gemini899** [comment]
another question, the smoothing option doesn't seam to work at least for it make no difference from 1 to 10

**Comment by SunOner** [comment]
I fixed mouse_smoothing. Try now.
