### ISSUE TITLE
arduino/yolo doesnt work in valorant

### ISSUE THREAD

**Issue by qwerd219** [SunOner/yolov8_aimbot#168]
When i go in a deathmatch or go into the shooting range in Valorant and rightclick it doesnt let my mouse move at the target 
i tried it on roblox there it works but not in Valorant
this is my config:
[Detection window]
detection_window_width = 384
detection_window_height = 216 

[Bettercam Capture]
Bettercam_capture = yes
bettercam_capture_fps = 60
bettercam_monitor_id = 0
bettercam_gpu_id = 0

[Obs capture]
Obs_capture = no
Obs_camera_id = 1
Obs_capture_fps = 30

# DEPRECATED
[win32 Capture]
win32_capture = no

[Aim settings]
body_y_offset = 0.35
hideout_targets = no
disable_headshot = no

[Hotkeys settings]
hotkey_targeting = RightMouseButton
hotkey_exit = F2
hotkey_pause = F3
hotkey_reload_config = F4

[Mouse settings]
mouse_dpi = 1000
mouse_sensitivity = 2
mouse_fov = 90
mouse_lock_target = no
mouse_auto_shoot = no
mouse_auto_aim = no
mouse_native = yes
mouse_triggerbot = no
mouse_move_by_arduino = no
mouse_shoot_by_arduino = no

[AI options]
# You can find new improved models here https://boosty.to/sunone
AI_model_path = sunxds_0.2.9.6.pt
AI_image_size = 320
AI_conf = 0.35
AI_iou = 0.1
AI_device = 0
AI_max_det = 10

[Overlay detector]
show_overlay_detector = no
show_overlay_boxes = yes
show_overlay_line = yes

[Debug window]
show_window = no
show_speed = no
show_fps = no
show_boxes = yes
show_labels = yes
show_conf = yes
show_target_line = yes
debug_window_always_on_top = yes
debug_window_scale_percent = 100
debug_window_name = Calculator

and this is my mouse script that i executed in arduino:
#include <hidboot.h>
#include <usbhub.h>
#include <Mouse.h>
#include <Wire.h>
#ifdef dobogusinclude
#include <spi4teensy3.h>
#endif
#include <SPI.h>
USB     Usb;
USBHub     Hub(&Usb);
HIDBoot < USB_HID_PROTOCOL_KEYBOARD | USB_HID_PROTOCOL_MOUSE > HidComposite(&Usb);
HIDBoot<USB_HID_PROTOCOL_MOUSE>    HidMouse(&Usb);

// Signed char can be between -128 to 127
int delta[2];
int negMax = -127;
int posMax = 127;

// Mouse
int lmb = 0;
int rmb = 0;
int mmb = 0;

class MouseRptParser : public MouseReportParser
{
  protected:
    void OnMouseMove(MOUSEINFO *mi);
    void OnLeftButtonUp(MOUSEINFO *mi);
    void OnLeftButtonDown(MOUSEINFO *mi);
    void OnRightButtonUp(MOUSEINFO *mi);
    void OnRightButtonDown(MOUSEINFO *mi);
    void OnMiddleButtonUp(MOUSEINFO *mi);
    void OnMiddleButtonDown(MOUSEINFO *mi);
};

void MouseRptParser::OnMouseMove(MOUSEINFO *mi)
{
  delta[0] = mi->dX;
  delta[1] = mi->dY;
};
void MouseRptParser::OnLeftButtonUp	(MOUSEINFO *mi)
{
  lmb = 0;
};
void MouseRptParser::OnLeftButtonDown	(MOUSEINFO *mi)
{
  lmb = 1;
};
void MouseRptParser::OnRightButtonUp	(MOUSEINFO *mi)
{
  rmb = 0;
};
void MouseRptParser::OnRightButtonDown	(MOUSEINFO *mi)
{
  rmb = 1;
};
void MouseRptParser::OnMiddleButtonUp	(MOUSEINFO *mi)
{
  mmb = 0;
};
void MouseRptParser::OnMiddleButtonDown	(MOUSEINFO *mi)
{
  mmb = 1;
};

MouseRptParser MousePrs;

void setup()
{
  Mouse.begin();
  Serial.begin( 115200 );
  Usb.Init();
  HidComposite.SetReportParser(1, &MousePrs);
  HidMouse.SetReportParser(0, &MousePrs);
}

void loop()
{
  delta[0] = 0;
  delta[1] = 0;
  Usb.Task();
  // Left Mouse
  if (lmb == 0){
    Mouse.release(MOUSE_LEFT);
  } else if (lmb == 1){
    Mouse.press(MOUSE_LEFT);
  }
  // Right Mouse
  if (rmb == 0){
    Mouse.release(MOUSE_RIGHT);
  } else if (rmb == 1){
    Mouse.press(MOUSE_RIGHT);
  }
  // Middle Mouse
  if (mmb == 0){
    Mouse.release(MOUSE_MIDDLE);
  } else if (mmb == 1){
    Mouse.press(MOUSE_MIDDLE);
  }

  if (Serial.available() > 0)
  {
    // Read Data
    String data = Serial.readStringUntil('x');

    // Gets demarcation between deltaX and DeltaY
    int ohHiMarc = data.indexOf(':');
    Serial.println(data);

    // DeltaX & DeltaY
    delta[0] = data.substring(0, ohHiMarc).toInt();
    delta[1] = data.substring(ohHiMarc + 1).toInt();

    handleX(delta[0]);
    handleY(delta[1]);
  } else{
    Mouse.move(delta[0], delta[1]);
  }
}

// Handle Moving of x 
void handleX(int dx){
  
  int spawns; 
  int remainder;
  
  if(dx < negMax)
  {
    // How many times we move mouse
    spawns = int(dx / negMax); 
    
    // How much we move after for loop
    remainder = int(dx % negMax);

    // Because we can only move 125 at a time,
    // we need a for loop to spawn multiple mouse events.
    for(int i = 0; i < spawns; i++)
    {
      Mouse.move(negMax , 0, 0);
    }
    // Move Remainder
    Mouse.move(remainder, 0, 0);
  } 
  else if (dx >= negMax && dx <= posMax)
  {
    Mouse.move(dx, 0, 0);
  }
  else if (dx > posMax)
  {
    // How many times we move mouse
    spawns = int(dx / posMax); 
    
    // How much we move after for loop
    remainder = int(dx % posMax);
    
    for(int i = 0; i < spawns; i++)
    {
      Mouse.move(posMax , 0, 0);
    }
    // Move Remainder
    Mouse.move(remainder, 0, 0);
  }
  
}

// Handle Moving of x 
void handleY(int dy){
  
  int spawns; 
  int remainder;
  // MindTrip, Neg is pos & Pos is Neg for move, hence the inverted pos & Neg
  if(dy < negMax)
  {
    // How many times we move mouse
    spawns = int(dy / negMax); 
    
    // How much we move after for loop. -1 converts to correct direction on arduino (pos,neg,neg,pos)
    remainder = int(dy % negMax);
    remainder *= -1;
    // Because we can only move 125 at a time,
    // we need a for loop to spawn multiple mouse events.
    for(int i = 0; i < spawns; i++)
    {
      Mouse.move(0, posMax, 0);
    }
    // Move Remainder
    Mouse.move(0, remainder, 0);
  } 
  else if (dy >= negMax && dy <= posMax)
  {
    dy *= -1;
    Mouse.move(0, dy, 0);
  }
  else if (dy > posMax)
  {
    // How many times we move mouse
    spawns = int(dy / posMax); 
    
    // How much we move after for loop
    remainder = int(dy % posMax);
    remainder *= -1;
    
    for(int i = 0; i < spawns; i++)
    {
      Mouse.move(0, negMax, 0);
    }
    // Move Remainder
    Mouse.move(0, remainder, 0);
  }
};

**Comment by SunOner** [comment]
Turn on Arduino in config.
mouse_move_by_arduino = yes

**Comment by SunOner** [comment]
It also won't work with your code that is uploaded to Arduino. I need to use the code from my repository with [Arduino.](https://github.com/SunOner/HID_Arduino)

**Comment by qwerd219** [comment]
From you tutorial it says i should place the extracted downloaded folder to C:\Users\tomco\OneDrive\Documents\Arduino\HID_Arduino but theres no such a path, when im in C:\Users\tomco\OneDrive\Documents\Arduino  theres only a folder which is libraries

**Comment by qwerd219** [comment]
in your tutorial it says i should put the repository into C:\Users\tomco\OneDrive\Documents\Arduino\HID_Arduino but in C:\Users\tomco\OneDrive\Documents\Arduino theres only the libraries folder

**Comment by qwerd219** [comment]
when i upload the HID_Arduino.ino i cant move my mouse

**Comment by SunOner** [comment]
Read install guide

**Comment by qwerd219** [comment]
when i switch to 9600 Baud i dont see the date of the input

**Comment by qwerd219** [comment]
okay ive done everything but when i run yolov8 it will load the aimbot but seconds later just let my mouse freeze

**Comment by cats-ui** [comment]
this method of arduino is detected in valorant dont expect to play more than week

**Comment by cats-ui** [comment]
also yolov8 in valorant is really dogshit u just need to make a simple colorbot( many people did that already), and get unique method of arduino spoof

**Comment by cats-ui** [comment]
dont cheat in gold
