### ISSUE TITLE
the updated version does not start

### ISSUE THREAD

**Issue by Stal33** [SunOner/yolov8_aimbot#17]
Hi! I downloaded the code that you updated yesterday, but it doesn't start and doesn't give any errors, just nothing happens, dxcam doesn't start. although your old version is working properly!

**Comment by SunOner** [comment]
Obs_capture and native_Windows_capture don't work either?

**Comment by Stal33** [comment]
I tried all three, but not in which the capture window did not open

**Comment by rhjnrhjn** [comment]
на секунду открылся главный и все. что я не так делаю? установил все как сказано карта 1060

**Comment by SunOner** [comment]
> на секунду открылся главный и все. что я не так делаю? установил все как сказано карта 1060

Я создал новый файл "checks.py". Запусти, посмотрим что у тебя не так.

**Comment by Stal33** [comment]
вот что мне выдал фаил PS C:\Users\abc1e\OneDrive\Рабочий стол\yolov8_aimbot-main (1)\yolov8_aimbot-main> python .\checks.py
python : Ultralytics YOLOv8.0.208  Python-3.11.6 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 10240MiB)
строка:1 знак:1
+ python .\checks.py
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Ultralytics YOL...3080, 10240MiB):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Setup complete  (20 CPUs, 12.8 GB RAM, 154.1/234.4 GB disk)
OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 12.85 GB
CPU                 12th Gen Intel Core(TM) i7-12700KF
CUDA                12.1
matplotlib           3.8.1>=3.3.0
numpy                1.26.1>=1.22.2
opencv-python        4.8.1.78>=4.6.0
pillow               10.1.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.31.0>=2.23.0
scipy                1.11.3>=1.4.1
torch                2.1.0+cu121>=1.8.0
torchvision          0.16.0+cu121>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.2>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.6
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

Cuda support: True
OpenCV version: 4.8.1
TensorRT version: 8.6.1
numpy version: 1.26.1
DXcam devices info:
Device[0] Output[0]: Res:(1920, 1080) Rot:0 Primary:True
Device[0] Output[1]: Res:(1600, 900) Rot:0 Primary:False

Traceback (most recent call last):
  File "C:\Users\abc1e\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\abc1e\OneDrive\Рабочий стол\yolov8_aimbot-main (1)\yolov8_aimbot-main\checks.py", line 73, in <module>
    run_checks()
  File "C:\Users\abc1e\OneDrive\Рабочий стол\yolov8_aimbot-main (1)\yolov8_aimbot-main\checks.py", line 23, in run_checks
    print('asyncio version: {0}'.format(importlib.metadata.version('asyncio')))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc1e\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 1008, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc1e\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abc1e\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for asyncio

**Comment by Stal33** [comment]
я установил asyncio

**Comment by Stal33** [comment]
теперь всё вот так PS C:\Users\abc1e\OneDrive\Рабочий стол\yolov8_aimbot-main (1)\yolov8_aimbot-main> python .\checks.py
python : Ultralytics YOLOv8.0.208  Python-3.11.6 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 10240MiB)
строка:1 знак:1
+ python .\checks.py
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Ultralytics YOL...3080, 10240MiB):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Setup complete  (20 CPUs, 12.8 GB RAM, 154.2/234.4 GB disk)
OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 12.85 GB
CPU                 12th Gen Intel Core(TM) i7-12700KF
CUDA                12.1
matplotlib           3.8.1>=3.3.0
numpy                1.26.1>=1.22.2
opencv-python        4.8.1.78>=4.6.0
pillow               10.1.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.31.0>=2.23.0
scipy                1.11.3>=1.4.1
torch                2.1.0+cu121>=1.8.0
torchvision          0.16.0+cu121>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.2>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.6
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

Cuda support: True
OpenCV version: 4.8.1
TensorRT version: 8.6.1
numpy version: 1.26.1
DXcam devices info:
Device[0] Output[0]: Res:(1920, 1080) Rot:0 Primary:True
Device[0] Output[1]: Res:(1600, 900) Rot:0 Primary:False

asyncio version: 3.4.3
Options file:

original_screen_width 1920
original_screen_height 1080 

screen_width 480
screen_height 300 

Dxcam_capture True
dxcam_capture_fps 30
dxcam_monitor_id 0
dxcam_gpu_id 0
dxcam_max_buffer_len 64 

Obs_capture False
Obs_camera_id 1
Obs_capture_fps 30 

native_Windows_capture False 

body_y_offset 0.35
hideout_targets True 

mouse_smoothing 1
mouse_auto_shoot False
mouse_auto_aim False
mouse_native False 

AI_model_path models/sunxds_0.2.1_nano_320.pt
AI_image_size 320
AI_conf 0.4
AI_iou 0.1
AI_device 0
AI_half True
AI_max_det 10
AI_verbose False 

show_window False
show_speed False
show_fps False
debug_window_scale_percent 100
debug_window_name Calculator 

Environment variables:

ALLUSERSPROFILE: C:\ProgramData
APPDATA: C:\Users\abc1e\AppData\Roaming
COMMONPROGRAMFILES: C:\Program Files\Common Files
COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432: C:\Program Files\Common Files
COMPUTERNAME: REVAN
COMSPEC: C:\Windows\system32\cmd.exe
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA_PATH_V12_1: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
DRIVERDATA: C:\Windows\System32\Drivers\DriverData
EFC_1784: 1
FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING: Default
HOMEDRIVE: C:
HOMEPATH: \Users\abc1e
INTELLIJ IDEA: D:\soft\IntelliJ IDEA 2023.1\bin;
INTELLIJ IDEA COMMUNITY EDITION: D:\IntelliJ IDEA Community Edition 2023.1\bin;
LOCALAPPDATA: C:\Users\abc1e\AppData\Local
LOGONSERVER: \\REVAN
NUMBER_OF_PROCESSORS: 20
ONEDRIVE: C:\Users\abc1e\OneDrive
ONEDRIVECONSUMER: C:\Users\abc1e\OneDrive
OS: Windows_NT
PATH: C:\Users\abc1e\AppData\Local\Programs\Python\Python311\Lib\site-packages\cv2\../../x64/vc14/bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bi
n;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\S
ystem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\N
VIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0\;C:\Users\abc1e\OneDrive\Рабочий стол\cudnn-w
indows-x86_64-8.9.4.25_cuda12-archive\bin;C:\Users\abc1e\OneDrive\Рабочий стол\TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0 (2)\TensorRT-8.6.1.6\lib;C:\Program Fi
les\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;C:\Program Files\Common Files\Oracle\Java\javapa
th;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corpo
ration\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0
\;C:\Users\abc1e\OneDrive\Рабочий стол\cudnn-windows-x86_64-8.9.4.25_cuda12-archive\bin;C:\Users\abc1e\OneDrive\Рабочий стол\TensorRT-8.6.1.6.Windows10.x86_64.cu
da-12.0 (2)\TensorRT-8.6.1.6\lib;C:\Program Files\NVIDIA Corp;C:\Users\abc1e\AppData\Local\Programs\Python\Python311
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
PROCESSOR_LEVEL: 6
PROCESSOR_REVISION: 9702
PROGRAMDATA: C:\ProgramData
PROGRAMFILES: C:\Program Files
PROGRAMFILES(X86): C:\Program Files (x86)
PROGRAMW6432: C:\Program Files
PSMODULEPATH: C:\Users\abc1e\OneDrive\Документы\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\M
odules
PUBLIC: C:\Users\Public
SESSIONNAME: Console
SYSTEMDRIVE: C:
SYSTEMROOT: C:\Windows
TEMP: C:\Users\abc1e\AppData\Local\Temp
TMP: C:\Users\abc1e\AppData\Local\Temp
USERDOMAIN: REVAN
USERDOMAIN_ROAMINGPROFILE: REVAN
USERNAME: abc1e
USERPROFILE: C:\Users\abc1e
WINDIR: C:\Windows
NUMEXPR_MAX_THREADS: 8
CUBLAS_WORKSPACE_CONFIG: :4096:8
TF_CPP_MIN_LOG_LEVEL: 2
CUDA_MODULE_LOADING: LAZY

**Comment by Stal33** [comment]
и всё ровно не запускается окно захвата экрана
