### ISSUE TITLE
Warface Ban

### ISSUE THREAD

**Issue by Somixc** [SunOner/yolov8_aimbot#171]
Warface bann, could it be because of the betterkam takeover?

**Comment by Somixc** [comment]
How to download your early versions without betterkam?

**Comment by Somixc** [comment]
I played with an early version of Obs_capture, everything was fine

**Comment by SunOner** [comment]
Obs_capture is also in this version, there are many reasons why the account could be blocked, and rather the main reason is not using adruino.
