### ISSUE TITLE
The mouse wobbles and fails to locate the target center correctly

### ISSUE THREAD

**Issue by 2430468136** [SunOner/yolov8_aimbot#173]
My Settings are 
mouse_dpi = 800
mouse_sensitivity =4
mouse_fov = 90
My setup includes a 4080 GPU and a 7800X3D CPU. The original DPI of my mouse is 2300. I have repeatedly changed the 'dpi', 'body_y_offset', and 'mouse_sensitivity' settings in the config file, but it seems to have no effect. In the OpenCV window, the target is accurately and quickly identified. However, when I manually move to the head of the character, the aim automatically bounces off. When it automatically locks on, it shifts to the bottom left and fails to accurately lock onto the target.
https://github.com/SunOner/yolov8_aimbot/assets/130272264/58b73e6e-13b4-406d-95f1-de6b3bd8d1c7

**Comment by Bazz0r** [comment]
Can you share the change please?
