### ISSUE TITLE
cant export in engine

### ISSUE THREAD

**Issue by Gemini899** [SunOner/yolov8_aimbot#18]
i managed to install tensorrt, but now if i try to convert my .pt to engine i get ONNX: starting export with onnx 1.15.0 opset 17... and then it seams to crash without saving the engine file, i am able to convert in onnx but for some reason with onnx it is super laggy i only get 7-8 fps.
this is the comand i use: C:\Users\PC\Downloads\yolov8 aim\yolov8_aimbot-main\models/best.pt" format=engine half=true device=0 workspace=8 imgsz=640 nms=True

i also tryied to train with your python script train_game.py with the same result it wont save the engine file

**Comment by Gemini899** [comment]
also could you add a FOV for the aimbot separate from the capture window?

**Comment by SunOner** [comment]
Can I see your options.py ? I have a feeling that I can help you with the speed boost.

**Comment by Gemini899** [comment]
# Screen resolution
original_screen_width = 2560
original_screen_height = 1440

# Object Search window resolution
screen_width = 380
screen_height = 380

# dxcam Capture method
Dxcam_capture = True
dxcam_capture_fps = 35 # More value, more mouse swing
dxcam_monitor_id = 0
dxcam_gpu_id = 0
dxcam_max_buffer_len = 64

# Obs capture method
Obs_capture = False
Obs_camera_id = 1
Obs_capture_fps = 30 # More value, more mouse swing

# Windows capture method
native_Windows_capture = False

# Aim settings
body_y_offset = -0.20
hideout_targets = False

# Mouse settings 
mouse_smoothing = 2 # 1 is default
mouse_auto_shoot = False
mouse_auto_aim = False
mouse_native = False

# AI options
AI_model_path = 'models/pubg.pt'
AI_image_size = 640
AI_conf = 0.35
AI_iou = 0.1
AI_device = 0
AI_half = True
AI_max_det = 10
AI_verbose = False

# Cv2 debug window settings
show_window = True
show_speed = True
show_fps = True
debug_window_scale_percent = 100
debug_window_name = 'Calculator'

**Comment by Gemini899** [comment]
i set body offset to -0.20 to help me with recoil control, would be nice if you could had a recoil control value that drag the mouse down while right-click is held down and left is held down.

that's the issue i get wen exporting in engine
![Immagine](https://github.com/SunOner/yolov8_aimbot/assets/89453273/cbb4d52c-4126-47e3-b21e-f90465cd5a93)

**Comment by SunOner** [comment]
Try:
1) cd C:/Users/PC/Downloads/yolov8 aim/yolov8_aimbot-main/
2) yolo export model="models/best.pt" format=engine half=true device=0 imgsz=640 verbose=true

**Comment by Gemini899** [comment]
i was able to fix the issue here is the fix,https://github.com/ultralytics/ultralytics/issues/5267
you need to uninstall onnx, onnxruntime-gpu, and onnxsim and then run export. This is with the latest version of Ultralytics, Pytorch 2.1, and Cuda 12.1.

However, it requires this EACH time to run export.

**Comment by Gemini899** [comment]
would you be able to add the Recoil control? it will improve the aimbot a lot since in some games like rust/pubg the gun kicks crazy, also would you be able to add a separate FOV to prevent jumping between targets so we can still have big search windows like 400x400 and also be able to accurately chose who to target.
i think this would help the aimbot a lot.
