### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by ArtiDevil** [SunOner/yolov8_aimbot#180]
![image](https://github.com/SunOner/yolov8_aimbot/assets/59886571/4ebcad3f-7e38-4674-ac64-24aba60278f7)

**Comment by ax16** [comment]
Skid check: what's 1 + 1 ? 

But yeah you have to install pytorch with cuda support. 
If you DO own Nvidia CUDA Graphics card:

Figure out your CUDA version:
`nvcc --version`
![image](https://github.com/SunOner/yolov8_aimbot/assets/47465168/01ff9c60-f6cf-457a-8d90-838d03d99573)
Then proceed to this fancy UI and submit your specs to generate pip install command with proper version !
Don't forget to uninstall the old version !
[https://pytorch.org/get-started/locally/](url)
![image](https://github.com/SunOner/yolov8_aimbot/assets/47465168/0606767a-5149-4a12-b360-3830015038aa)

**Comment by Ludik89** [comment]
I have exactly the same problem as in the photo, but your solution did not help ): 
![изображение_2024-01-11_133204268](https://github.com/SunOner/yolov8_aimbot/assets/156297735/16f2dcf9-6795-45bc-8ff9-e22dd1cb8bd0)

**Comment by Gamekir** [comment]
привет таже самая ошибка
![relf](https://github.com/SunOner/yolov8_aimbot/assets/156313829/58ac1a52-8fcc-4b41-9ca9-ba9d67f39751)
![ошибка](https://github.com/SunOner/yolov8_aimbot/assets/156313829/88a20bd1-a9fa-471d-b036-6a633f117625)

**Comment by SunOner** [comment]
1) `pip uninstall torch torchvision torchaudio`
2) `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`
