### ISSUE TITLE
Периодически вылетает ошибка

### ISSUE THREAD

**Issue by zipzip332** [SunOner/yolov8_aimbot#183]
File "\yolov8_aimbot\logic\mouse.py", line 169, in run
    Arduino.move(int(x), int(y))
                 ^^^^^^
ValueError: cannot convert float NaN to integer

**Comment by zipzip332** [comment]
проблема не критична, проявляется не очень часто, но приходится заморачиваться с перезапуском во время игры.
Использую ардуино если что
[config(ini).txt](https://github.com/SunOner/yolov8_aimbot/files/13901234/config.ini.txt)

**Comment by SunOner** [comment]
Это давно исправленная ошибка. Обнови приложение.
