### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by Gamekir** [SunOner/yolov8_aimbot#184]
![relf](https://github.com/SunOner/yolov8_aimbot/assets/156313829/4ffa8c71-43a3-432e-98c2-78a44516bce6)
![ошибка](https://github.com/SunOner/yolov8_aimbot/assets/156313829/9dc30e18-0059-44aa-9914-4f4c5df97b3f)

**Comment by SunOner** [comment]
1) `pip uninstall torch torchvision torchaudio`
2 ) `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`
