### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ludik89** [SunOner/yolov8_aimbot#185]
![cmd](https://github.com/SunOner/yolov8_aimbot/assets/156297735/15b75782-55db-47bd-a8ac-18f12f76d87a)

**Comment by SunOner** [comment]
1) `pip uninstall torch torchvision torchaudio`
2) `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

**Comment by Ludik89** [comment]
Thanks, everything worked
