### ISSUE TITLE
не запускается калькулятор

### ISSUE THREAD

**Issue by rhjnrhjn** [SunOner/yolov8_aimbot#19]
данная модель не запускает калькулятор. пишет нет tensorrt ( он есть ). выпуск 18.11.2023 утром все работает до сих пор 
как мне сохранить свой движок после экспорта? При поиске цели (пкм)  мышь бросает в сторону

**Comment by SunOner** [comment]
Запусти checks.py и скопируй вывод сюда.

**Comment by rhjnrhjn** [comment]
Traceback (most recent call last):
    File ''C\Users\Z\Downloads\yolov8_aimbot-main (4)\yolov8_aimbot-main\checks.py'', line 4, in<module>
   import tensorrt 
ModuleNotFoundError: No module named 'tensorrt'

**Comment by SunOner** [comment]
Не правильно установлен tensorrt, прочти официальную инструкцию по установке. (Zip file installation).

**Comment by rhjnrhjn** [comment]
В старой версии все работает же

**Comment by Gemini899** [comment]
add me on discord ill tell you how to install tensorrt,instead, i am unable to compile "export" to engine it starts the process but it doest save.
this is my discord 0xcf5450

**Comment by rhjnrhjn** [comment]
язык общения какой будет?
