### ISSUE TITLE
TensorRT: export failure ❌ 30.4s: 'NoneType' object does not support the context manager protocol

### ISSUE THREAD

**Issue by shellykagann** [SunOner/yolov8_aimbot#199]
![无标题](https://github.com/SunOner/yolov8_aimbot/assets/161372401/d13f45e1-99e1-4df8-9b36-01ddd9770bb2)

TypeError: 'NoneType' object does not support the context manager protocol

Nvidia graphics card=gtx 960

**Comment by SunOner** [comment]
Try to reinstall torch.
