### ISSUE TITLE
Problems regarding lost imports

### ISSUE THREAD

**Issue by TJF0910** [SunOner/yolov8_aimbot#203]
![Screenshot 2024-03-12 000958](https://github.com/SunOner/yolov8_aimbot/assets/106958924/fbe9108b-9079-4244-88c4-b6ff7aee3e72)
hello im kinda stuck but dont know how to get back the modules that i imported, any help?

**Comment by SunOner** [comment]
It looks like an incorrectly chosen interpreter.

**Comment by TJF0910** [comment]
interpreter as in its running in VSCode? Im new and slow when it comes to coding and python but even when I runs it in command prompt, this kinda happens? Is it because it cant detect the NumPy, Cv2 ...... modules?
![Screenshot 2024-03-12 074524](https://github.com/SunOner/yolov8_aimbot/assets/106958924/414abe9c-9b1b-4421-bb08-a515cbf9342b)
