### ISSUE TITLE
About setting values

### ISSUE THREAD

**Issue by Jotalz** [SunOner/yolov8_aimbot#205]
what's the `mouse_fov_width` and `mouse_fov_highth` mean？Sorry I didn't understand your comment,are they the coordinates of the character's initial perspective in game?

**Comment by SunOner** [comment]
https://www.pcgamingwiki.com/wiki/Glossary:Field_of_view_(FOV)#Vertical_and_horizontal_FOV

**Comment by Jotalz** [comment]
Thank you!This helps a lot

**Comment by Jotalz** [comment]
Aiming is very messy when I use it in apex, am I missing any settings?
I opened the Debug window settings and observed that the recognition was accurate, but there was a problem with the aiming.
In order to save space, the number of frames of the recorded video is very low, which is not a performance lag.
https://github.com/SunOner/yolov8_aimbot/assets/57427866/864324f1-df98-4ab2-bad8-b13f8a4c7d69

This is my [config.txt](https://github.com/SunOner/yolov8_aimbot/files/14616120/config.txt)
The module I used another author's 640 size training model specifically for apex.

**Comment by SunOner** [comment]
Try to enable instant replay in nvidia experience so that the card raises the frequencies.

**Comment by Jotalz** [comment]
> Try to enable instant replay in nvidia experience so that the card raises the frequencies.
sorry, what I'm saying is that the bot-aiming position is incorrect,the stuttering is just because the frame rate of the video file is low,you can see my game fps is normal.
