### ISSUE TITLE
关于tensorrt-8.6.1-cp311-none-win_amd64.whl包下载失败

### ISSUE THREAD

**Issue by SuperRonin** [SunOner/yolov8_aimbot#206]
此安装包已经没有了
tensorrt-8.6.1-cp311-none-win_amd64.whl

官方发布的包中，已经没有此版本
https://pypi.nvidia.com/tensorrt-bindings/

**Comment by SunOner** [comment]
Try to install from [here](https://pypi.nvidia.com/tensorrt/)
