### ISSUE TITLE
Doesn't work in game

### ISSUE THREAD

**Issue by spout5** [SunOner/yolov8_aimbot#210]
Hello, please help me.
1) I installed it according to the instructions (https://github.com/SunOner/yolov8_aimbot/blob/main/docs/ru/install_guide_ru.md)

2) Next, I installed BetterCam using the “pip install Bettercam” command.

3) After which I launch AIM, there are no errors, I launch the game, but AIM does not work in the game.
What could be the problem?
![Снимок экрана (5)](https://github.com/SunOner/yolov8_aimbot/assets/143263911/6b38cf3e-7003-4e76-8d2a-9385a84cb834)

**Comment by OzymoGit** [comment]
what game did you try it on? if the game have kernal anticheat you will need a special driver for mouse input

**Comment by spout5** [comment]
> в какой игре ты это пробовал? Если в игре есть античит-ядро, вам понадобится специальный драйвер для ввода с помощью мыши.

Game Warface. I launch it and nothing happens, no mouse response

**Comment by spout5** [comment]
> what game did you try it on? if the game have kernal anticheat you will need a special driver for mouse input

Game Warface. I launch it and nothing happens, no mouse response.

**Comment by SunOner** [comment]
This problem has been solved in the discord server for a long time.
