### ISSUE TITLE
Doesnt move mouse

### ISSUE THREAD

**Issue by Hubabubatz** [SunOner/yolov8_aimbot#219]
WARNING: Export the model to `.engine` for better performance!
WARNING: win32api is detected in some games.
WARNING: Using standard libraries for mouse moving such as `win32` or `Ghub driver` without bypassing, for example, how Arduino can speed up the account blocking process, use it at your own risk.
WARNING: Using standard libraries for mouse shooting such as `win32` or `Ghub driver` without bypassing, for example, how Arduino can speed up the account blocking process, use it at your own risk.
Yolov8 Aimbot is started! (Version 0.5.6)

i followed the autoinstalled guide 

config ini: 
[Detection window]
detection_window_width = 384
detection_window_height = 216 

[Capture Methods]
Bettercam_capture = True
bettercam_capture_fps = 60
bettercam_monitor_id = 0
bettercam_gpu_id = 0
Obs_capture = False
Obs_camera_id = auto
Obs_capture_fps = 30

[Aim]
body_y_offset = 0.35
hideout_targets = False
disable_headshot = False

[Hotkeys]
hotkey_targeting = RightMouseButton
hotkey_exit = F2
hotkey_pause = F3
hotkey_reload_config = F4

[Mouse]
mouse_dpi = 1000
mouse_sensitivity = 1
mouse_fov_width = 60
mouse_fov_height = 45
mouse_lock_target = False
mouse_auto_aim = False
mouse_ghub = False

[Shooting]
auto_shoot = true
triggerbot = true
force_click = False

[Arduino]
arduino_move = false
arduino_shoot = false
arduino_port = auto
arduino_baudrate = 9600
arduino_16_bit_mouse = False

[AI]
# You can find new improved models here https://boosty.to/sunone
AI_model_name = sunxds_0.4.1.pt
AI_model_image_size = 480
AI_conf = 0.35
AI_device = 0
AI_enable_AMD = False
AI_mouse_net = False

[Debug window]
show_window = False
show_detection_speed = False
show_window_fps = False
show_boxes = True
show_labels = True
show_conf = True
show_target_line = True
show_target_prediction_line = True
debug_window_always_on_top = True
spawn_window_pos_x = 100
spawn_window_pos_y = 100
debug_window_scale_percent = 100

also when i download tensorRT in helper, it happens nothing

**Comment by rhjn13** [comment]
Do you have an Arduino?  If not, then why did you change something in the config?  What game is this?

**Comment by Hubabubatz** [comment]
yes arduino and hostshield i didnt change anytghing

**Comment by rhjn13** [comment]
> да, Arduino и HostShield, я ничего не менял

Did you boost the Arduino power supply?  Soldered?

**Comment by SunOner** [comment]
Use ghub or arduino.
