### ISSUE TITLE
при запуски main не чего не происходит

### ISSUE THREAD

**Issue by Stal33** [SunOner/yolov8_aimbot#22]
Привет ещё раз я всё с темже обновлёная вами версия не запускается ошибок не каких не выдаёт она как бы запустилась но окно dxcam  не появляется Старая версия работает исправно запускаются все три модели может что то не так с файлом main? Фаил checks запускал вроде не каких ошибок не выдаёт.
![image](https://github.com/SunOner/yolov8_aimbot/assets/130001714/98ed33f2-5bf7-42fb-92ed-5dde82bc396c)
![image](https://github.com/SunOner/yolov8_aimbot/assets/130001714/7f9f2713-4570-407f-b6eb-a55670b3c257)
![image](https://github.com/SunOner/yolov8_aimbot/assets/130001714/92b34eb2-0aab-4ce2-8e50-7b5ae983c98c)

**Comment by rhjnrhjn** [comment]
Dxcam просто отключено. Проверь те в игре

**Comment by Stal33** [comment]
> Dxcam просто отключено. Проверь меня в игре. Написано показать витрину Ложь. Если исправить True, то сделайте то, что запустили

Спасибо вопрос снят)))
