### ISSUE TITLE
AIM bot не наводит мышку и не стреляет

### ISSUE THREAD

**Issue by Estomel** [SunOner/yolov8_aimbot#220]
настроил все по инструкции, ошибок нет, `show_window = True`  показывает что отслеживание работает и модели игроков спокойно определяются но наводки нет совсем

![jmePyUeqPlg](https://github.com/SunOner/yolov8_aimbot/assets/103012285/1736793f-fd52-4eca-bca6-f1fa63240a30)

как исправить?

**Comment by SunOner** [comment]
В какой то конкретной игре?

**Comment by Hubabubatz** [comment]
Конечно, SunOner, я могу рассмотреть вашу проблему. Что именно вас беспокоит?

**Comment by Hubabubatz** [comment]
Конечно, SunOner, я могу рассмотреть вашу проблему. Что именно вас беспокоит?

**Comment by Estomel** [comment]
> В какой то конкретной игре?

WarFace
