### ISSUE TITLE
please can i get dataset images and labels for this project?

### ISSUE THREAD

**Issue by gtr667gwy45** [SunOner/yolov8_aimbot#221]
@SunOner  hi please would you mind kindly share dataset images and labels for this project? please thank you very much i really appreciate it

**Comment by SunOner** [comment]
Hi. Check [this](https://github.com/SunOner/yolov8_aimbot/issues/14)

**Comment by gtr667gwy45** [comment]
@SunOner  ok but you could blur or hide your personal information like your in game name. i want your dataset. please thank you very much
