### ISSUE TITLE
AI Model Image Size

### ISSUE THREAD

**Issue by zekurom** [SunOner/yolov8_aimbot#222]
I don't quite understand what the "AI Model Image Size" fully means, I've tried doing some research but no luck, could I please have a brief explanation?

**Comment by HavokMaster** [comment]
> I don't quite understand what the "AI Model Image Size" fully means, I've tried doing some research but no luck, could I please have a brief explanation?

The AI Model Image Size is actually passed on to the input variable "imgsz" of the YOLO model. The imgsz in turn refers to the size of the image which will be passed on to the model for inference. So lets say this parameter is set to 640 (which is actually default), now lets say the resolution of the screen capture of the gameplay is 1080p (just an example). So before the image is passed to the model to detect for enemies it will actually be resized to 640x640 resolution (AI Model Image Size). This makes the inference a lot quicker than directly passing the 1080p image.

Here is the description from ultralytics official documentation:
![def](https://github.com/SunOner/yolov8_aimbot/assets/53501215/7db9f301-2198-4b8d-acc7-0adcc7127e9b)

I hope this helps you out!
