### ISSUE TITLE
Script fails after three seconds using Arduino mouse

### ISSUE THREAD

**Issue by mq0227** [SunOner/yolov8_aimbot#225]
I tested the mouse in Arduino IDE and everything works fine.
![image](https://github.com/SunOner/yolov8_aimbot/assets/145292831/e28aac4e-5a20-477d-9ac1-f8c8a1ecb299)
But when I execute run.py, everything is fine, but after 3 seconds the mouse is uncontrollable. And no error is returned
![image](https://github.com/SunOner/yolov8_aimbot/assets/145292831/4653d200-3d40-4cae-b140-801e4e7cebb8)
[Detection window]
detection_window_width = 384
detection_window_height = 216 

[Capture Methods]
Bettercam_capture = True
bettercam_capture_fps = 144
bettercam_monitor_id = 0
bettercam_gpu_id = 0
Obs_capture = False
Obs_camera_id = auto
Obs_capture_fps = 30

[Aim]
body_y_offset = 0.3
hideout_targets = False
disable_headshot = False

[Hotkeys]
hotkey_targeting = RightMouseButton
hotkey_exit = F2
hotkey_pause = F3
hotkey_reload_config = F4

[Mouse]
mouse_dpi = 800
mouse_sensitivity = 1
mouse_fov_width = 60
mouse_fov_height = 45
mouse_lock_target = False
mouse_auto_aim = False
mouse_ghub = False

[Shooting]
auto_shoot = False
triggerbot = False
force_click = False

[Arduino]
arduino_move = True
arduino_shoot = True
arduino_port = COM5
arduino_baudrate = 9600
arduino_16_bit_mouse = True

[AI]
# You can find new improved models here https://boosty.to/sunone
AI_model_name = sunxds_0.4.1.pt
AI_model_image_size = 480
AI_conf = 0.1
AI_device = cpu
AI_enable_AMD = true
AI_mouse_net = False

[Debug window]
show_window = False
show_detection_speed = False
show_window_fps = False
show_boxes = True
show_labels = True
show_conf = True
show_target_line = True
show_target_prediction_line = True
debug_window_always_on_top = True
spawn_window_pos_x = 100
spawn_window_pos_y = 100
debug_window_scale_percent = 100

**Comment by mq0227** [comment]
Additional Notes: I soldered the g-powered part as you did, and also used 12v to power the Arduino power strip

**Comment by herokoko** [comment]
I'm having the same problem, please how can I fix it

**Comment by mq0227** [comment]
You should try executing the script using the administrator command window

**Comment by mq0227** [comment]
> 我也遇到了同样的问题，请问我该如何解决
You should try executing the script using the administrator command window
