### ISSUE TITLE
Не работает yolov8_aimbot через AMD

### ISSUE THREAD

**Issue by Daetes** [SunOner/yolov8_aimbot#226]
у меня RX5700 все скачал как по инструкции увидел то что для амд надо zluda,pytorch и ROCm все скачал вроде без ошибок, в конфиге даже поставил true для амд , в общем запускаю аимбот когда захожу в игру Warface то ни на кого не наводится и ничего не работает, лазил в кофниге переустанавливал все без толку, что делать

**Comment by SunOner** [comment]
В некоторых играх придётся использовать другие методы ввода мыши, например такие как ghub или arduino.

**Comment by Daetes** [comment]
> В некоторых играх придётся использовать другие методы ввода мыши, например такие как ghub или arduino.
все скачал по новой ардуино купил подключил но когда захожу в варфейс очень долго наводится больше 3 секунд
