### ISSUE TITLE
Mouse doesnt move with native mouse set to false

### ISSUE THREAD

**Issue by SouljaVR** [SunOner/yolov8_aimbot#24]
Hi,

For some reason when **not** using native mouse mode, the mouse does not move for me at all. Like it is unable to target anything with right click, even with detections available. Any idea what could be causing this? I use a logitech mouse myself with ghub and perhaps it conflicts with the logitech dll you seem to be using, I havent been able to get it to work at all though. Thank you for your work, I did also send you a message on discord regarding this.

**Comment by SunOner** [comment]
Will be added back in the next update.
