### ISSUE TITLE
the mouse cannot aimed at the target

### ISSUE THREAD

**Issue by Aubreybit** [SunOner/yolov8_aimbot#25]
The debug window showed the box,but the mouse only aimed the target within a few seconds of switching back to the game window from the terminal..I have tried running in windowed mode and running the program as an administrator.

**Comment by SunOner** [comment]
What is the name of the game?

**Comment by Aubreybit** [comment]
> What is the name of the game?

CS2

**Comment by mark66641** [comment]
здраствуйте, хотел выразить благодарность за проделанную работу по аим асист для варфейса. 
возник вопрос все сделал как на видео загруженой на ютуб, но при открывании прицела наводиться в стену, возможно ли это исправить? спасибо

**Comment by EraseRewin** [comment]
Same problem, all is right installed and all work.But even with mouse smooth 1 and capture frame 30fps, the aim is unstable, and schake like crazy.I hope for a fix.
Great Job

**Comment by cats-ui** [comment]
hey, try to disable Enhance Pointer Precision in Windows(google) also try  to disable Raw Input in games you are trying to use yolov8 aim

**Comment by cats-ui** [comment]
@EraseRewin @Aubreybit

**Comment by cats-ui** [comment]
> здраствуйте, хотел выразить благодарность за проделанную работу по аим асист для варфейса. возник вопрос все сделал как на видео загруженой на ютуб, но при открывании прицела наводиться в стену, возможно ли это исправить? спасибо

Это ошибки в детектах, они появляются у тебя из за старой модели, подпишись(платно) на бусти, скачай модели, и эти ошибки будут намного меньше происходить с каждым апдейтом моделей.

**Comment by EraseRewin** [comment]
> hey, try to disable Enhance Pointer Precision in Windows(google) also try  to disable Raw Input in games you are trying to use yolov8 aim

Disabled many times ago :)

**Comment by cats-ui** [comment]
> > hey, try to disable Enhance Pointer Precision in Windows(google) also try  to disable Raw Input in games you are trying to use yolov8 aim
> 
> Disabled many times ago :)

what game then?

**Comment by EraseRewin** [comment]
> > > hey, try to disable Enhance Pointer Precision in Windows(google) also try  to disable Raw Input in games you are trying to use yolov8 aim
> > 
> > Disabled many times ago :)
> 
> what game then? gpu, oc?

Warface, overclock gpu (3070 TI) off.

**Comment by cats-ui** [comment]
> > > > hey, try to disable Enhance Pointer Precision in Windows(google) also try  to disable Raw Input in games you are trying to use yolov8 aim
> > > 
> > > 
> > > Disabled many times ago :)
> > 
> > 
> > what game then? gpu, oc?
> 
> Warface, overclock gpu (3070 TI) off.

send ur settings here, what oc?

**Comment by EraseRewin** [comment]
> > > > > hey, try to disable Enhance Pointer Precision in Windows(google) also try  to disable Raw Input in games you are trying to use yolov8 aim
> > > > 
> > > > 
> > > > Disabled many times ago :)
> > > 
> > > 
> > > what game then? gpu, oc?
> > 
> > Warface, overclock gpu (3070 TI) off.
> 
> send ur settings here, what oc?

Sorry what you mean with OC?
Setting in game:
Sensitivity mouse 17
Dpi 1200 (logitech mouse ghub)
Resolution video 2k
Play windowed
Graphics medium settings 
Fps limit 144 (fix)

Settings in code:
Just changed smooth from 2 to 1, i need to check with other values
Capure frame 30 fps

**Comment by cats-ui** [comment]
> > > > > > hey, try to disable Enhance Pointer Precision in Windows(google) also try  to disable Raw Input in games you are trying to use yolov8 aim
> > > > > 
> > > > > 
> > > > > Disabled many times ago :)
> > > > 
> > > > 
> > > > what game then? gpu, oc?
> > > 
> > > 
> > > Warface, overclock gpu (3070 TI) off.
> > 
> > 
> > send ur settings here, what oc?
> 
> Sorry what you mean with OC? Setting in game: Sensitivity mouse 17 Dpi 1200 (logitech mouse ghub) Resolution video 2k Play windowed Graphics medium settings Fps limit 144 (fix)
> 
> Settings in code: Just changed smooth from 2 to 1, i need to check with other values Capure frame 30 fps

ok, put sens  6 ingame ghub - 800 dpi, put smooth 3-4. post results also  update some of the files there(they got updated) like main.py and options.py 
put capture frame 60, low settings ingame

**Comment by cats-ui** [comment]
and can u make a clip after u did allat?

**Comment by EraseRewin** [comment]
> and can u make a clip after u did allat? 

Of course, this evening i will try and ivwill post here. Thanks

**Comment by cats-ui** [comment]
> > and can u make a clip after u did allat?
> 
> Of course, this evening i will try and i will post here. Thanks

👍

**Comment by EraseRewin** [comment]
Ok , tested with;
Mouse Ghub Dpi 800
Game mouse sensitivity 8 (game)
Low graphic (game)
Code:
Mouse smooth 4
Capture fps 60
Installed code update!
Tested only in poligon and work well.
Thanks Dev!
Tomorrow i wil post a clip ingame.
RTX3070TI is ok!

**Comment by cats-ui** [comment]
> Ok , tested with; Mouse Ghub Dpi 800 Game mouse sensitivity 8 (game) Low graphic (game) Code: Mouse smooth 4 Capture fps 60 Installed code update! Tested only in poligon and work well. Thanks Dev! Tomorrow i wil post a clip ingame. RTX3070TI is ok!

im not a dev bro but thats fair 🤷‍♂️ lemme see a clip and im glad i helped u with this problem
