### ISSUE TITLE
I use names that will soon no longer be available.

### ISSUE THREAD

**Issue by progeroffline** [SunOner/yolov8_aimbot#28]
On startup I get this error, in a constant loop. The entire log is filled with this error. I think that you should pay attention to this and change the names of the variables before the library is released.
`
WARNING ⚠️ 'boxes' is deprecated and will be removed in 'ultralytics 8.2' in the future. Please use 'show_boxes' instead.`

**Comment by SunOner** [comment]
Fixed.
