### ISSUE TITLE
yolo error

### ISSUE THREAD

**Issue by prada-hvh** [SunOner/yolov8_aimbot#33]
Model loaded. None
Traceback (most recent call last):
  File "C:\Users\mofa\Desktop\yolik\main.py", line 145, in <module>
    init()
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mofa\Desktop\yolik\main.py", line 86, in init
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 234, in predict
    self.predictor = (predictor or self._smart_load('predictor'))(overrides=args, _callbacks=self.callbacks)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 86, in __init__
    self.args = get_cfg(cfg, overrides)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 113, in get_cfg
    check_dict_alignment(cfg, overrides)
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 202, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'show_boxes' is not a valid YOLO argument. Similar arguments are i.e. ['show_labels=True', 'boxes=True', 'show_conf=True'].

    Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
    
    
Ultralytics YOLOv8.0.205  Python-3.11.6 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)
Setup complete  (8 CPUs, 15.9 GB RAM, 196.1/475.8 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 15.94 GB
CPU                 Intel Core(TM) i3-10100F 3.60GHz
CUDA                12.1

matplotlib           3.8.1>=3.3.0
numpy                1.26.1>=1.22.2
opencv-python        4.8.1.78>=4.6.0
pillow               9.3.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.28.1>=2.23.0
scipy                1.11.3>=1.4.1
torch                2.1.0+cu121>=1.8.0
torchvision          0.16.0+cu121>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.2>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.6
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

**Comment by SunOner** [comment]
Pip install Ultralytics — upgrade

**Comment by prada-hvh** [comment]
Сообщение = 'NoneType' object has no attribute 'create_execution_context'
  Источник = C:\Users\mofa\Desktop\yolik\main.py
  Трассировка стека:
  File "C:\Users\mofa\Desktop\yolik\main.py", line 86, in init (Current frame)
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "C:\Users\mofa\Desktop\yolik\main.py", line 145, in <module>
    init()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
