### ISSUE TITLE
export to engine dont work

### ISSUE THREAD

**Issue by strangerkarelli** [SunOner/yolov8_aimbot#34]
![kfK-siS-B9o](https://github.com/SunOner/yolov8_aimbot/assets/152617442/9e40b0c2-e78d-4b27-89b1-cf132e880c6b)

**Comment by ExternalBitchesss** [comment]
У меня так же не знаю что делать help

**Comment by SunOner** [comment]
Pip uninstall onnx
The try to export.

**Comment by ExternalBitchesss** [comment]
> Владелец

Пробовал но как будто не ускорилось

**Comment by ExternalBitchesss** [comment]
> > > Владелец
> > 
> > 
> > Пробовал, но не ускорилось
> 
> Она долго экспортируется, около пяти минут.

Смотри она останавливается и ничего не происходит 5 секунд проходит и все

**Comment by strangerkarelli** [comment]
> Pip uninstall onnx The try to export.

![image](https://github.com/SunOner/yolov8_aimbot/assets/152617442/3de37ff9-30dc-4775-a795-0170a814a6de)
