### ISSUE TITLE
main.py torch.cuda.is_available(): False

### ISSUE THREAD

**Issue by Hanched** [SunOner/yolov8_aimbot#37]
Здравствуйте, делаю все как в гайде.ru указано, не работает. После ввода python main.py выдает следующее:C:\Program Files\yolov8_aimbot-main>python main.py
Model loaded. None
Ultralytics YOLOv8.0.221 🚀 Python-3.11.6 torch-2.1.1+cpu
Traceback (most recent call last):
  File "C:\Program Files\yolov8_aimbot-main\main.py", line 145, in <module>
    init()
  File "C:\Users\rx 580 hlam no drive\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\yolov8_aimbot-main\main.py", line 86, in init
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "C:\Users\rx 580 hlam no drive\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 232, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\rx 580 hlam no drive\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 318, in setup_model
    device=select_device(self.args.device, verbose=verbose),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rx 580 hlam no drive\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\torch_utils.py", line 119, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

Видео карта 1050. Если что то еще нужно скинуть, я скину. Переустановка pytrch не помогает
помогите пажалуйста

**Comment by Hanched** [comment]
И может ли это каким то образом работать на RX580?

**Comment by Hanched** [comment]
C:\Program Files\yolov8_aimbot-main>python options.py

C:\Program Files\yolov8_aimbot-main>checks.py
Ultralytics YOLOv8.0.221 🚀 Python-3.11.6 torch-2.1.1+cpu CPU (AMD Ryzen 5 2600 Six-Core Processor)
Setup complete ✅ (12 CPUs, 11.9 GB RAM, 84.4/111.7 GB disk)

OS                  Windows-10-10.0.19042-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 11.93 GB
CPU                 AMD Ryzen 5 2600 Six-Core Processor
CUDA                None

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.26.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

Cuda support True
OpenCV version: 4.8.1
Model summary: 225 layers, 3012798 parameters, 0 gradients, 8.2 GFLOPs
(225, 3012798, 0, 8.2038272)
numpy version: 1.26.2
DXcam devices info:
Device[0] Output[0]: Res:(1920, 1080) Rot:0 Primary:True

asyncio version: 3.4.3
Options file checks:

original_screen_width 1920
original_screen_height 1080

screen_width 480
screen_height 300

Dxcam_capture True
dxcam_capture_fps 60
dxcam_monitor_id 0
dxcam_gpu_id 0
dxcam_max_buffer_len 64

Obs_capture False
Obs_camera_id 1
Obs_capture_fps 30

native_Windows_capture False

body_y_offset 0.35
hideout_targets True

mouse_smoothing 2
mouse_auto_shoot False
mouse_auto_aim False
mouse_native True

AI_model_path models/sunxds_0.2.1_nano_320.pt
AI_image_size 320
AI_conf 0.35
AI_iou 0.1
AI_device 0
AI_max_det 10
show_window False
show_speed False
show_fps False
show_boxes True
show_labels True
show_conf True
debug_window_scale_percent 100
debug_window_name Calculator

Environment variables:

ALLUSERSPROFILE: C:\ProgramData
APPDATA: C:\Users\rx 580 hlam no drive\AppData\Roaming
BUILD: Microsoft Windows [Version 10.0.19042.631]
CHASSISTYPE: 3
COMMONPROGRAMFILES: C:\Program Files\Common Files
COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432: C:\Program Files\Common Files
COMPUTERNAME: DESKTOP-K6VP7EG
COMSPEC: C:\Windows\system32\cmd.exe
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA_PATH_V12_1: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
DRIVERDATA: C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING: Default
HOMEDRIVE: C:
HOMEPATH: \Users\rx 580 hlam no drive
LOCALAPPDATA: C:\Users\rx 580 hlam no drive\AppData\Local
LOGONSERVER: \\DESKTOP-K6VP7EG
MANUFACTURER: System manufacturer
MAX_CLOCK_SPEED: 3400
MODEL: System Product Name
NUMBER_OF_CORES: 6
NUMBER_OF_PROCESSORS: 12
OS: Windows_NT
PATH: C:\Users\rx 580 hlam no drive\AppData\Local\Programs\Python\Python311\Lib\site-packages\cv2\../../x64/vc14/bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program files\yolov8_aimbot-main\TensorRT-8.6.1.6\lib;C:\Users\rx 580 hlam no drive\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\rx 580 hlam no drive\AppData\Local\Programs\Python\Python311\;C:\Users\rx 580 hlam no drive\AppData\Local\Microsoft\WindowsApps;;C:\Users\rx 580 hlam no drive\AppData\Local\Programs\Microsoft VS Code\bin
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
PROCESSOR_LEVEL: 23
PROCESSOR_REVISION: 0802
PROGRAMDATA: C:\ProgramData
PROGRAMFILES: C:\Program Files
PROGRAMFILES(X86): C:\Program Files (x86)
PROGRAMW6432: C:\Program Files
PROMPT: $P$G
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC: C:\Users\Public
SESSIONNAME: Console
SVCHOSTSPLIT: 13536508
SYSTEMDRIVE: C:
SYSTEMROOT: C:\Windows
TEMP: C:\Users\rx 580 hlam no drive\AppData\Local\Temp
TMP: C:\Users\rx 580 hlam no drive\AppData\Local\Temp
USERDOMAIN: DESKTOP-K6VP7EG
USERDOMAIN_ROAMINGPROFILE: DESKTOP-K6VP7EG
USERNAME: rx 580 hlam no drive
USERPROFILE: C:\Users\rx 580 hlam no drive
WINDIR: C:\Windows
NUMEXPR_MAX_THREADS: 8
CUBLAS_WORKSPACE_CONFIG: :4096:8
TF_CPP_MIN_LOG_LEVEL: 2

C:\Program Files\yolov8_aimbot-main>

**Comment by Hanched** [comment]
переустановил pytorch, не помогает. Погуглил, пишут, что cuda9.0 не поддерживается 1050. Но при этом смотрю другой источник, 1050 поддерживает cuda. Что к чему не ясно

**Comment by Weser87** [comment]
> переустановил Pytorch, не помогает. Погуглил, пишет, что cuda9.0 не включает 1050. Но при этом смотрю другой источник, 1050 поддерживает cuda. Что к чему непонятно

В моем случае были проблемы только в экспорте.
У меня 1050-ti. Решение: установить Cuda10.1

**Comment by Hanched** [comment]
Не воркает, накатил даже на чистую винду, всеравно по барабану. Не хочет работать адекватно

**Comment by cats-ui** [comment]
Попробуй поставить CPU в девайсах, вместо видеокарты, опубликуй результат

> Не воркает, накатил даже на чистую винду, всеравно по барабану. Не хочет работать адекватно

**Comment by cats-ui** [comment]
> Не воркает, накатил даже на чистую винду, всеравно по барабану. Не хочет работать адекватно

Попробуй CUDA 9.0 еще
