### ISSUE TITLE
Вопрос по поводу карт Amd

### ISSUE THREAD

**Issue by aszx0923** [SunOner/yolov8_aimbot#51]
Хотелось бы уточнить для незрячего,который только начинает знакомится с сие чудом,работает ли аим асист для видео карт амд,и если нет,есть ли какие то аналоги ,в частности интересует для проекта под названием warface,готов приобрести за нн-ую сумму,заранее благодарю за ответ.

**Comment by cats-ui** [comment]
ахахахаахаха блять

**Comment by cats-ui** [comment]
никто не тестил амд видюхи, но для них есть альтернатива в лице OpenCL, учитывай что она будет не так производительна как нвидиа, потому что амд кусок дерьма ебаного

**Comment by SunOner** [comment]
Запускай onnx модель.

**Comment by Jolenkov123** [comment]
Как запустить onnx модель?))
\
