### ISSUE TITLE
yolo export format=engine,No response

### ISSUE THREAD

**Issue by ckx382** [SunOner/yolov8_aimbot#52]
yolo export model="models/sunxds_0.2.1_nano_320.pt" format=engine half=true device=0 imgsz=320
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics YOLOv8.0.222 🚀 Python-3.11.6 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)
Model summary (fused): 168 layers, 3007598 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'models\sunxds_0.2.1_nano_320.pt' with input shape (1, 3, 320, 320) BCHW and output shape(s) (1, 14, 2100) (5.9 MB)

ONNX: starting export with onnx 1.15.0 opset 17...

And It's over.No response

**Comment by SunOner** [comment]
'Pip uninstall onnx'
And try export again
