### ISSUE TITLE
The gtx2080ti is unavailable 

### ISSUE THREAD

**Issue by ckx382** [SunOner/yolov8_aimbot#53]
python main.py

It runs fine, but after 30 seconds, it exits automatically and only onnx format can be used

**Comment by cats-ui** [comment]
> python main.py
> 
> It runs fine, but after 30 seconds, it exits automatically and only onnx format can be used

run checks.py, send results

**Comment by SunOner** [comment]
Because there is no such graphics card **GTX** 2080ti

**Comment by cats-ui** [comment]
just do what guide says, why did u got 12.3? 

> @cats-ui I am using nvidia cuda12.3, is the version too high and must be 12.1? But when I installed 12.1, it also automatically exited. Is it because CUDA was not completely uninstalled?

**Comment by ckx382** [comment]
@cats-ui Are you sure the problem with CUDA12.3? I installed 12.1, The problem is the same. Please look at the screenshot,The process automatically exited. If the debug window is opened, the debug window stops responding.
![image](https://github.com/SunOner/yolov8_aimbot/assets/19352373/4a5c948c-31ba-4ba9-b8da-bd466b9c3813)

**Comment by ckx382** [comment]
After reinstall PyTorch, the problem seems to have been solved
But a new problem appeared, I was just testing the program yesterday,No run success, just run, my Battlefield 5 account was banned, what code did he detect?What feature code need to be changed?
@cats-ui @SunOner

**Comment by cats-ui** [comment]
I don't know, we need more information on how you got banned. What do you think? I'm going to guess?


> After reinstall PyTorch, the problem seems to have been solved But a new problem appeared, I was just testing the program yesterday,No run success, just run, my Battlefield 5 account was banned, what code did he detect?What feature code need to be changed?

**Comment by ckx382** [comment]
> I don't know, we need more information on how you got banned. What do you think? I'm going to guess?
> 
> > After reinstall PyTorch, the problem seems to have been solved But a new problem appeared, I was just testing the program yesterday,No run success, just run, my Battlefield 5 account was banned, what code did he detect?What feature code need to be changed?

It should be that mouse move has been detected. Can the mouse feature code be modified to bypass detection?Or use the driver to control the mouse.

**Comment by cats-ui** [comment]
> > I don't know, we need more information on how you got banned. What do you think? I'm going to guess?
> > > After reinstall PyTorch, the problem seems to have been solved But a new problem appeared, I was just testing the program yesterday,No run success, just run, my Battlefield 5 account was banned, what code did he detect?What feature code need to be changed?
> 
> It should be that mouse move has been detected. Can the mouse feature code be modified to bypass detection?Or use the driver to control the mouse.

I think u are probably right, but i dont know exactly cuz i didnt play bf2042 once in my life. to bypass mouse movement u need a signed undetected kernel driver

**Comment by cats-ui** [comment]
> > I don't know, we need more information on how you got banned. What do you think? I'm going to guess?
> > > After reinstall PyTorch, the problem seems to have been solved But a new problem appeared, I was just testing the program yesterday,No run success, just run, my Battlefield 5 account was banned, what code did he detect?What feature code need to be changed?
> 
> It should be that mouse move has been detected. Can the mouse feature code be modified to bypass detection?Or use the driver to control the mouse.

if u will give me a bf2042  account, i will test it

**Comment by cats-ui** [comment]
> @cats-ui i dont have bf2042,only have bf5
Then give me bf5
