### ISSUE TITLE
Models Load "none"

### ISSUE THREAD

**Issue by Shveps4032000** [SunOner/yolov8_aimbot#55]
Ultralytics YOLOv8.0.222 🚀 Python-3.11.6 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
Model summary (fused): 168 layers, 3007598 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'models\sunxds_0.2.1_nano_320.pt' with input shape (1, 3, 320, 320) BCHW and output shape(s) (1, 14, 2100) (5.9 MB)

ONNX: starting export with onnx 1.15.0 opset 17...

Is there steps to load models ?

**Comment by cats-ui** [comment]
привет, есть тг? легче там помочь

**Comment by cats-ui** [comment]
pip uninstall onnx
run export again

**Comment by Shveps4032000** [comment]
.
