### ISSUE TITLE
gpu compatibility 3060

### ISSUE THREAD

**Issue by theangelomerkel** [SunOner/yolov8_aimbot#59]
![Screenshot 2023-12-07 204852](https://github.com/SunOner/yolov8_aimbot/assets/115698476/1ac3ea78-8a74-4791-9ac9-cf6b9819084c)
hello i get an issue with my hardware gpu 3060 how can i fix it?

**Comment by SunOner** [comment]
Are you using a laptop?

**Comment by theangelomerkel** [comment]
Yes

**Comment by SunOner** [comment]
Try changing the `dxcam_gpu_id` parameter to 1, 2 or 3. Most likely this is due to the fact that the index of the integrated graphics card is at the beginning. If it doesn't work, then you need to use other ways to capture images, like `Obs_capture` or `native_Windows_capture'.

**Comment by theangelomerkel** [comment]
> Are you using a laptop?

Yes why?
