### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by rhjnrhjn** [SunOner/yolov8_aimbot#6]
Как запустить этот аим бот на более старых картах? Для примера на gt 740

**Comment by SunOner** [comment]
Не думаю что это хорошая идея запускать ИИ на 740 карте. В теории он должен работать на ней так как CUDA ядра у неё имеются.

**Comment by rhjnrhjn** [comment]
pytorch and pc  не видят  cuda

**Comment by SunOner** [comment]
Они удалили поддержку старых карт.
https://github.com/pytorch/pytorch/issues/14681

**Comment by rhjnrhjn** [comment]
на секунду main  открывается и все. что я не так делаю? установил все как сказано

**Comment by inuokaaa** [comment]
почему в cmd когда я пишу:
yolov8_aimbot-main>yolov8_aimbot-main>yolov8_aimbot-main>pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

в строке пишется 
"yolov8_aimbot-main" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

Хотя я правильно всё делал

**Comment by SunOner** [comment]
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/ceda79df-c7f9-4fe0-a58e-659ad7dc4f72)
мне кажется или файлов не хватет?

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/7fc6106e-c453-4854-afcc-53225e87f457)
Следующая панель

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/e2d469d2-2b1a-4c2d-8519-a479eb3931e2)
что делать если не устанавливается?

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/65d66b5f-e4aa-4654-a8ca-e548da33a280)
бро можешь скинуть эту строку я не понимаю как она пишется

**Comment by SunOner** [comment]
yolo export model="models/sunxds_0.2.1_nano_320.pt" format=engine half=true device=0 imgsz=320

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/42798fa9-f52b-44ad-9513-6e93ba373ab0)
должна заработать?
Просто с открытой панелью в вф заходить?

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/d57cc221-0838-4481-8e00-aaabd20431b8)
помоги решить пожалуйста
