### ISSUE TITLE
по поводу amd

### ISSUE THREAD

**Issue by djizi** [SunOner/yolov8_aimbot#60]
Подскажи пожалуйста, как запустить на amd, что скачать нужно, сабку если что оформлю на бусти, гуглил альтернативу на амд, показывал рком, но не воркает, он не видит cuda через кмд когда вписываю команду :(

(     raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch. )
![Screenshot_25](https://github.com/SunOner/yolov8_aimbot/assets/134390017/e0d8ea96-5152-45d7-97f5-b036409b69e4)

**Comment by cats-ui** [comment]
ты такой богатый! если что сабку оформишь нша бусти) лучше быстрее карту продай
обнови дравйера установи rocm и установи другие ваще требования, ток хуй знает какие, гуглить надо

**Comment by djizi** [comment]
> ты такой богатый! если что сабку оформишь нша бусти) лучше быстрее карту продай обнови дравйера установи rocm и установи другие ваще требования, ток хуй знает какие, гуглить надо другую версию торча(под свою видюху), там потести, чет поделай сам, материал найдешь

да рх как по мне за эти деньги для игры получше будет нвид за те же деньги что и рх580, проблем никаких нету ( мое мнение, до этого юзал gtx 1050 ) по поводу файлов, уже рком скачал, драва обновил, про торч вообще братик не ебу, че куда, щас вроде гуглю, даже если найду как его сетапнуть или какую кмд писать

**Comment by djizi** [comment]
> ты такой богатый! если что сабку оформишь нша бусти) лучше быстрее карту продай обнови дравйера установи rocm и установи другие ваще требования, ток хуй знает какие, гуглить надо другую версию торча(под свою видюху), там потести, чет поделай сам, материал найдешь

я вроде б уже нашел даже, рком видимо откатить надо до более старой версии там же и торч есть ( https://github.com/xuhuisheng/rocm-gfx803/issues/27#issuecomment-1534048619 )
но там если кмд только , че мне с ними делать? 
![Screenshot_26](https://github.com/SunOner/yolov8_aimbot/assets/134390017/b8cb93b1-ee50-4a79-9a0b-83b187c6ba90)
![Screenshot_27](https://github.com/SunOner/yolov8_aimbot/assets/134390017/39a58e30-0120-4adc-9daa-6a57aeeb92d5)
