### ISSUE TITLE
Ошибка в экспорте .pt в .engine.  export failure ❌ 6.1s: No module named 'onnx'

### ISSUE THREAD

**Issue by Kirillh993** [SunOner/yolov8_aimbot#62]
вот что появляется когда пытаюсь прописать команду yolo export model="models/sunxds_0.2.1_nano_320.pt" format=engine half=true device=0 imgsz=320
 как исправить?
![Screenshot_2](https://github.com/SunOner/yolov8_aimbot/assets/153268853/3e903bdf-917f-4440-9e04-4f06c003cc5c)

файлы в папке лежат
![Screenshot_4](https://github.com/SunOner/yolov8_aimbot/assets/153268853/1de7da45-bc7a-4855-87ab-7f0d78b5db3e)

**Comment by cats-ui** [comment]
install onnx install onnxsim

**Comment by Kirillh993** [comment]
> установить onnx установить onnxsim

как включить автообновление?

**Comment by cats-ui** [comment]
> > установить onnx установить onnxsim
> 
> как включить автообновление?

выключить антивирус нахуй

**Comment by cats-ui** [comment]
reinstall ultralytics doesnt work
pip3 install --upgrade ultralytics doesnt work

**Comment by cats-ui** [comment]
@SunOner закрывай проблема решена
