### ISSUE TITLE
WARNING ⚠️ NMS time limit 0.550s exceeded

### ISSUE THREAD

**Issue by djizi** [SunOner/yolov8_aimbot#63]
WARNING ⚠️ NMS time limit 0.550s exceeded
что делац

**Comment by SunOner** [comment]
Какое у тебя железо?

**Comment by djizi** [comment]
i5 3570k
12GB
gtx1660 super

**Comment by djizi** [comment]
> Какое у тебя железо?

+ еще проц хавает пиздец как, когда не вписываю что бы перешел вформат ехе, больше чем варфейс тотже

**Comment by cats-ui** [comment]
Привет, попробуй увеличить iou
