### ISSUE TITLE
Не могу выключить нейронку

### ISSUE THREAD

**Issue by zTew** [SunOner/yolov8_aimbot#65]
Такая проблема, не запускаю cmd, захожу поиграть просто, но все равно нейронка работает,до наводит на соперника хотя я ее не включал, как ее можно выключить?
Помогите пожалуйста

**Comment by cats-ui** [comment]
привет, я думаю это все у тебя в голове

**Comment by cats-ui** [comment]
Pip install durka

**Comment by Weser87** [comment]
stop the script on f2
