### ISSUE TITLE
OSError: [WinError 126] Не найден указанный модуль. Error loading 

### ISSUE THREAD

**Issue by djizi** [SunOner/yolov8_aimbot#66]
OSError: [WinError 126] Не найден указанный модуль. Error loading "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.

У друга проблема, как ее решить? вроде был там тикет такой же, но не помогло когда др куду скачал, карта 1050 Ti

**Comment by cats-ui** [comment]
Check questions.md

**Comment by cats-ui** [comment]
закрывай issue
