### ISSUE TITLE
Ошибка экспорта

### ISSUE THREAD

**Issue by Kirillh993** [SunOner/yolov8_aimbot#68]
Когда установлен модуль «onnx» ничего не происходит:
![Screenshot_9](https://github.com/SunOner/yolov8_aimbot/assets/153268853/f3a6e5e7-c498-4931-8aba-02f665163349)

Когда прописываю Pip uninstall onnx, как было в рекомендацих 
![Screenshot_10](https://github.com/SunOner/yolov8_aimbot/assets/153268853/a8259800-dc1e-4c46-87ad-04170c501afa)

**Comment by cats-ui** [comment]
зачем ты открыл два реквеста сразу? что это изменит?

**Comment by Kirillh993** [comment]
> зачем ты открыл два реквеста сразу? что это изменит?

старый удалиь могу

**Comment by cats-ui** [comment]
@SunOner закрываай проблема решена
