### ISSUE TITLE
проблема с ультрачетотам)

### ISSUE THREAD

**Issue by denis1999808** [SunOner/yolov8_aimbot#72]
Microsoft Windows [Version 10.0.19045.3693]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\igoty\Desktop\yolov8_aimbot-main>checks.py
install ultralytics: pip install ultralytics

C:\Users\igoty\Desktop\yolov8_aimbot-main>

как установить скажите пожалуйста

**Comment by denis1999808** [comment]
исправил все и пишет теперь вот че C:\Users\igoty\Desktop\yolov8_aimbot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\igoty\Desktop\yolov8_aimbot-main\main.py", line 6, in <module>
    import win32con, win32api
ModuleNotFoundError: No module named 'win32con' че делать ?

**Comment by SunOner** [comment]
pip install ultralytics

**Comment by denis1999808** [comment]
исправил все и пишет теперь вот че C:\Users\igoty\Desktop\yolov8_aimbot-main>python main.py
Traceback (most recent call last):
File "C:\Users\igoty\Desktop\yolov8_aimbot-main\main.py", line 6, in
import win32con, win32api
ModuleNotFoundError: No module named 'win32con' че делать ?

**Comment by SunOner** [comment]
Pip install -r requirements.txt

**Comment by SunOner** [comment]
Посмотри туториал как устанавливать правильно пожалуйста.
