### ISSUE TITLE
модель не найдена

### ISSUE THREAD

**Issue by denis1999808** [SunOner/yolov8_aimbot#73]
исправил все и пишет теперь вот че C:\Users\igoty\Desktop\yolov8_aimbot-main>python main.py
Traceback (most recent call last):
File "C:\Users\igoty\Desktop\yolov8_aimbot-main\main.py", line 6, in
import win32con, win32api
ModuleNotFoundError: No module named 'win32con' че делать ?

**Comment by cats-ui** [comment]
py install pywin32
