### ISSUE TITLE
настройка

### ISSUE THREAD

**Issue by denis1999808** [SunOner/yolov8_aimbot#74]
Кто то может скинуть настройки чтобы аимило четко не трясся прицел в стороны нвидиа 1050 на 4 гб стоит можете скинуть сетап ?

**Comment by cats-ui** [comment]
делай сам, могу только подсказать что за что отвечает 
mouse_break_force int: Eliminates unnecessary mouse acceleration.
mouse_smoothing float: Smoothing when moving the mouse.

**Comment by cats-ui** [comment]
закрывай issue

**Comment by denis1999808** [comment]
можешь кинуть свои настройки и сенс в игре?

**Comment by cats-ui** [comment]
> можешь кинуть свои настройки и сенс в игре?

блять ты что глупый? я же написал тебе делац сам и дал всю инфу

**Comment by cats-ui** [comment]
я не играю варфейс, нахуй он мне нужен? поэтому и не даю кфг

**Comment by denis1999808** [comment]
у меня короче прицел уводит вверх ссильно и таращит его влево вправо эти параметры в какую сторону делать уменьшение или прибавление ?

**Comment by cats-ui** [comment]
пробуй сам дениска, ты хочешь чтобы тебе припадали все и ты шел ебал весь варфейс ?

**Comment by Weser87** [comment]
> у меня перемены прицел уводит вверх сильно и таращит его влево вправо эти параметры в какую сторону делать уменьшение или прибавление ?

Скорее у вас стоит оконный режим, что отделяет центр экрана от прицела, поставьте оконный без рамок или полный экранный (лучше полный экранный)
Тряска прицела можно убрать с помощью mouse_smoothing, зависит от вашей сенсы в игре, если ваша сенса выше 5, ставьте ~1.5 и более
