### ISSUE TITLE
Не экспортируется.

### ISSUE THREAD

**Issue by MorningParadise** [SunOner/yolov8_aimbot#75]
raise ValueError(f"Invalid export format='{fmt}'. Valid formats are {fmts}")
ValueError: Invalid export format='pt'. Valid formats are ('torchscript', 'onnx', 'openvino', 'engine', 'coreml', 'saved_model', 'pb', 'tflite', 'edgetpu', 'tfjs', 'paddle', 'ncnn')

**Comment by cats-ui** [comment]
что вводишь когда экспортируешь?

**Comment by SunOner** [comment]
Ты экспортируешь .pt в .pt
