### ISSUE TITLE
Можно ли создать модель для PUBG? 

### ISSUE THREAD

**Issue by JakeEpps55** [SunOner/yolov8_aimbot#77]
Нашел модели на пабг, но они идут в фотографиях, ну в принципе да, я посмотрел что по ним и делается модель, но как саму модель по этим фото сделать? Больше всего это англоязычный обзоры, которые мне не помогают

**Comment by SunOner** [comment]
Посмотри к примеру этот [урок](https://habr.com/ru/articles/714232/) по тренировке модели, только за место пре-тренированных моделей yolov8n.pt/yolov8s.pt/yolov8m.pt используй мою, и за место coco8.yaml используй game.yaml. В дальнейшем в репозитории появится информация как обучить модель.

**Comment by JakeEpps55** [comment]
Спасибо, ты хороший человек, всем пытаешься помочь, рассказать и подсказать! Надеюсь у меня получится

**Comment by JakeEpps55** [comment]
> Посмотри к примеру этот [урок](https://habr.com/ru/articles/714232/) по тренировке модели, только за место пре-тренированных моделей yolov8n.pt/yolov8s.pt/yolov8m.pt используй мою, и за место coco8.yaml используй game.yaml. В дальнейшем в репозитории появится информация как обучить модель.

А ты вообще как считаешь, можно ли сделать чит для пабга на этой репозитории ?

**Comment by SunOner** [comment]
Модели на бусти немного обучены на pubg.
