### ISSUE TITLE
Tha aimbot is open but no aimbot is active

### ISSUE THREAD

**Issue by D00TO** [SunOner/yolov8_aimbot#79]
I have followed the installation instructions and done every thing correctly, and when opening main.py file
it says
Model loaded. None
Aimbot is started. Enjoy!
[Right mouse button] - Aiming at the target
[F2] - EXIT

in-game, I don't see any aimbot activity, playing on Destiny 2.

**Comment by cats-ui** [comment]
укажи путь до модели ai_model_path

**Comment by SunOner** [comment]
Are you playing in full-screen mode?

**Comment by cats-ui** [comment]
> Are you playing in full-screen mode?

так у него модель дже не загружена

**Comment by SunOner** [comment]
> > Are you playing in full-screen mode?
> 
> так у него модель дже не загружена

Это баг.

**Comment by cats-ui** [comment]
> in-game, I don't see any aimbot activity, playing on Destiny 2.

**Comment by D00TO** [comment]
> Are you playing in full-screen mode?

No I'm playing in windowed borderless mode, and the AI_model_path is already set, even pressing F2 while playing doesnt close the CMD window, I need to click on it and PRESS F2.

**Comment by cats-ui** [comment]
> > Are you playing in full-screen mode?
> 
> No I'm playing in windowed borderless mode, and the AI_model_path is already set, even pressing F2 while playing doesnt close the CMD window, I need to click on it and PRESS F2.

make a video where u run a cv2 “calculator” that shows how yolov8 detects an enemy in game after that show that ur aim is not working
that would be helpful, thanks

**Comment by D00TO** [comment]
> > > Are you playing in full-screen mode?
> > 
> > 
> > No I'm playing in windowed borderless mode, and the AI_model_path is already set, even pressing F2 while playing doesnt close the CMD window, I need to click on it and PRESS F2.
> 
> make a video where u run a cv2 “calculator” that shows how yolov8 detects an enemy in game after that show that ur aim is not working that would be helpful, thanks

what is CV2 "calculator" and how to open it and how to show you yolov8 detecting enemies?
just in short

HOW?

**Comment by cats-ui** [comment]
> > > > Are you playing in full-screen mode?
> > > 
> > > 
> > > No I'm playing in windowed borderless mode, and the AI_model_path is already set, even pressing F2 while playing doesnt close the CMD window, I need to click on it and PRESS F2.
> > 
> > 
> > make a video where u run a cv2 “calculator” that shows how yolov8 detects an enemy in game after that show that ur aim is not working that would be helpful, thanks
> 
> what is CV2 "calculator" and how to open it and how to show you yolov8 detecting enemies? just in short
> 
> HOW?

Cv2 debug window settings:

show_window bool: Shows the OpenCV2 window for visual feedback.

**Comment by D00TO** [comment]
> > > Are you playing in full-screen mode?
> > 
> > 
> > No I'm playing in windowed borderless mode, and the AI_model_path is already set, even pressing F2 while playing doesnt close the CMD window, I need to click on it and PRESS F2.
> 
> make a video where u run a cv2 “calculator” that shows how yolov8 detects an enemy in game after that show that ur aim is not working that would be helpful, thanks

https://www.youtube.com/watch?v=apNvtRHn9MU
here is the video

**Comment by SunOner** [comment]
Start aimbot from cmd, and don't touch console vindow. Try it.

**Comment by D00TO** [comment]
> Start aimbot from cmd, and don't touch console vindow. Try it.

how start from cmd, and not touch it?

**Comment by SunOner** [comment]
> > Start aimbot from cmd, and don't touch console vindow. Try it.
> 
> how start from cmd, and not touch it?

https://github.com/SunOner/yolov8_aimbot/blob/main/docs/en/questions_en.md

**Comment by D00TO** [comment]
> Start aimbot from cmd, and don't touch console vindow. Try it.

it doesn't work, even presing F2 doesn't close the CMD, maybe the cmd go in power saving mode when switching windows?

**Comment by cats-ui** [comment]
https://github.com/SunOner/yolov8_aimbot/issues/92

**Comment by D00TO** [comment]
> #92

well, im not a programmer you know, how to know if it's MY CUDA and how to fix it?

**Comment by cats-ui** [comment]
> > #92
> 
> well, im not a programmer you know, how to know if it's MY CUDA and how to fix it?

u still have this issue? u dont need to put so much effort in that man. if ur gonna share ur soul to devil im gonna connect to ur brain and try to fix it

**Comment by D00TO** [comment]
> > > #92
> > 
> > 
> > well, im not a programmer you know, how to know if it's MY CUDA and how to fix it?
> 
> u still have this issue? u dont need to put so much effort in that man. if ur gonna share ur soul to devil im gonna connect to ur brain and try to fix it

still and no, I won't share my soul to devil, it worth more than him and his cult altogether.
