### ISSUE TITLE
 How can I make it also work with both the right and left mouse buttons? At the moment it is only active on the left

### ISSUE THREAD

**Issue by Allmight0000** [SunOner/yolov8_aimbot#8]
How can I make it also work with both the right and left mouse buttons? At the moment it is only active on the left

Does it no longer need the Logitech drive?

**Comment by SunOner** [comment]
> Does it no longer need the Logitech drive?
At this stage of development I would like to abandon the Logitech driver..

Just change the following function if you want it to work on the right mouse button:
`win32api.GetAsyncKeyState(win32con.VK_RBUTTON) and auto_aim == False or win32api.GetAsyncKeyState(win32con.VK_LBUTTON) and auto_aim == False:`
