### ISSUE TITLE
в cmd открывшаяся от папки yolov8 пишет что  

### ISSUE THREAD

**Issue by inuokaaa** [SunOner/yolov8_aimbot#80]
"yolov8_aimbot-main" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
как решить, всё правильно делал

**Comment by SunOner** [comment]
Пришли скриншот консоли

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/432cd2d5-9f5b-4b24-83da-aa02474c1fd4)

**Comment by inuokaaa** [comment]
ч делать

**Comment by cats-ui** [comment]
> ч делать

АХААХАХАХААХАХХАА БРАТАН

**Comment by cats-ui** [comment]
AVERAGE WARFACE PLAYER 🔥

**Comment by inuokaaa** [comment]
помоги лучше братанчик

**Comment by cats-ui** [comment]
> помоги лучше братанчик
что я могу сделать если у тебя low iq
