### ISSUE TITLE
Ошибка файлов при запуске

### ISSUE THREAD

**Issue by inuokaaa** [SunOner/yolov8_aimbot#81]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/23f2a30a-331f-42f8-8e64-182823083d8c)
почему-то выдаёт ошибку при самом последнем вводе строки 
yolo export model="models/sunxds_0.2.1_nano_320.pt" format=engine half=true device=0 imgsz=320

**Comment by cats-ui** [comment]
copy the lib files to CUDA/11.x/bin

**Comment by cats-ui** [comment]
https://github.com/NVIDIA/TensorRT/issues/3252

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/c427feb6-d8ac-4f18-a3a2-27b790706f51)
ничего не поменялось

**Comment by cats-ui** [comment]
> NVIDIA/TensorRT#3252

https://github.com/NVIDIA/TensorRT/issues/3252
