### ISSUE TITLE
FileNotFoundError: Could not find: cublasLt64_12.dll. Is it on your PATH?

### ISSUE THREAD

**Issue by djizi** [SunOner/yolov8_aimbot#83]
после того как написал yolo export model="models/sunxds_0.3.5.pt" format=engine half=true device=0 imgsz=640
Длл качал закинул в сус32 и сусвов64 и нихуя:(
до этого играл в .pt но говорят же engine лучше
![image](https://github.com/SunOner/yolov8_aimbot/assets/134390017/41a71f4e-e783-437d-9ec8-1f62951b1f58)

**Comment by cats-ui** [comment]
https://github.com/tensorflow/tensorflow/issues/40108

**Comment by djizi** [comment]
> [тензорный поток/тензорный поток#40108](https://github.com/tensorflow/tensorflow/issues/40108)

FileNotFoundError: Could not find: cudnn64_8.dll. Is it on your PATH? 
Теперь эта ошибка)0

**Comment by djizi** [comment]
все решил ошибку, надо было длл скачать и перекинуть в .bin спасибо
