### ISSUE TITLE
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

### ISSUE THREAD

**Issue by 2662007798** [SunOner/yolov8_aimbot#85]
E:\yolov8_aimbot-main>python run.py
PT Model loaded.
Aimbot is started. Enjoy!
[Right mouse button] - Aiming at the target
[F2] - EXIT
Traceback (most recent call last):
  File "E:\yolov8_aimbot-main\run.py", line 169, in <module>
    init()
  File "C:\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\yolov8_aimbot-main\run.py", line 106, in init
    frame = get_new_frame()
  File "E:\yolov8_aimbot-main\logic\frame.py", line 24, in get_new_frame
    dx = dxcam.create(device_idx=dxcam_monitor_id, output_idx=dxcam_gpu_id, output_color="BGR", max_buffer_len=dxcam_max_buffer_len)
  File "C:\Python310\lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
  File "C:\Python310\lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
  File "C:\Python310\lib\site-packages\dxcam\dxcam.py", line 33, in __init__
    self._duplicator: Duplicator = Duplicator(
  File "<string>", line 6, in __init__
  File "C:\Python310\lib\site-packages\dxcam\core\duplicator.py", line 19, in __post_init__
    output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, '指定的设备接口或功能级别在此系统上不受支持。', (None, None, None, 0, None))
Exception ignored in: <function DXCamera.__del__ at 0x00000206DB5B7EB0>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "C:\Python310\lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "C:\Python310\lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

I updated the graphics card driver but it still doesn't work. I don't know why

why  pls  help me！！！！！！！！！！！

**Comment by cats-ui** [comment]
https://github.com/SunOner/yolov8_aimbot/issues/27

**Comment by 2662007798** [comment]
我似乎没有找到解决方案...... 抱歉




阿生
***@***.***







                       
Original Email
                       
                     

Sender:"cat"< ***@***.*** &gt;;

Sent Time:2023/12/11 23:01

To:"SunOner/yolov8_aimbot"< ***@***.*** &gt;;

Cc recipient:"2662007798"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [SunOner/yolov8_aimbot] AttributeError: &#39;DXCamera&#39; object has noattribute &#39;is_capturing&#39; (Issue #85)




 
Когда люди блять научатся смотреть старые иссуе?

**Comment by cats-ui** [comment]
> 我似乎没有找到解决方案...... 抱歉 阿生 ***@***.*** Original Email Sender:"cat"< ***@***.*** &gt;; Sent Time:2023/12/11 23:01 To:"SunOner/yolov8_aimbot"< ***@***.*** &gt;; Cc recipient:"[2662007798](tel:2662007798)"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;; Subject:Re: [SunOner/yolov8_aimbot] AttributeError: &#39;DXCamera&#39; object has noattribute &#39;is_capturing&#39; (Issue #85) Когда люди блять научатся смотреть старые иссуе? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

wtf bro?

**Comment by 2662007798** [comment]
> > 我似乎没有找到解决方案...... 抱歉 阿生 _**@**_.*** Original Email Sender:"cat"< _**@**_.*** >; Sent Time:2023/12/11 23:01 To:"SunOner/yolov8_aimbot"< _**@**_.*** >; Cc recipient:"2662007798"< _**@**_.*** >;"Author"< _**@**_.*** >; Subject:Re: [SunOner/yolov8_aimbot] AttributeError: 'DXCamera' object has noattribute 'is_capturing' (Issue #85) Когда люди блять научатся смотреть старые иссуе? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> wtf bro?


How can I solve this problem? is it the problem of my laptop Nvida graphics card?

**Comment by 2662007798** [comment]
Python versions 3.12-3.10 have been tried, but it's the same problem. 
Including the driver is already the latest version. Dx version is 12.

**Comment by cats-ui** [comment]
https://github.com/SunOner/yolov8_aimbot/issues/27

**Comment by 2662007798** [comment]
> #27
Thank you！！！ bro    mua mua mua 
I can't wait to go back and try.
