### ISSUE TITLE
Что сделал не правильно?

### ISSUE THREAD

**Issue by hafizov444** [SunOner/yolov8_aimbot#86]
![JaKMBfp6WLs](https://github.com/SunOner/yolov8_aimbot/assets/153525168/1871a0e0-b10b-4a53-b44b-93f24c1c1ef5)

**Comment by cats-ui** [comment]
pip install numpy

**Comment by hafizov444** [comment]
> pip install numpy

Сделал, все тоже самое

**Comment by cats-ui** [comment]
> > pip install numpy
> 
> Сделал, все тоже самое

https://www.microsoft.com/en-US/Download/confirmation.aspx?id=48145

**Comment by cats-ui** [comment]
после установки этой хуйни, перезагрузись, а вообще лучше переустанови pip install --upgrade numpy

**Comment by hafizov444** [comment]
> после установки этой хуйни, перезагрузись, а вообще лучше переустанови pip install --upgrade numpy

Так, одно пофиксил, теперь второе вылезло 
Запускал в оконном, в фулл не работает
![sPtvdAYfG1w](https://github.com/SunOner/yolov8_aimbot/assets/153525168/83a41436-c869-490f-9187-e979254613f8)

**Comment by cats-ui** [comment]
> > после установки этой хуйни, перезагрузись, а вообще лучше переустанови pip install --upgrade numpy
> 
> Так, одно пофиксил, теперь второе вылезло Запускал в оконном, в фулл не работает ![sPtvdAYfG1w](https://private-user-images.githubusercontent.com/153525168/289604967-83a41436-c869-490f-9187-e979254613f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTMwNTUsIm5iZiI6MTcwMjMxMjc1NSwicGF0aCI6Ii8xNTM1MjUxNjgvMjg5NjA0OTY3LTgzYTQxNDM2LWM4NjktNDkwZi05MTg3LWU5NzkyNTQ2MTNmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNjM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmMwYTg5MzYzYjA5NzIyYjFkODg5ZGU5MzU4MDNmYzhiYTc3NzM3Njc4NWJmMzJjZTdkYTBhZTlhZDJhZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DEYVl_zIi1jk2XeEhDXV5Udd_NzjLzFtj4t-udDXVwA)

так тебе это фиксить не надо? поддержки полного экрана нету, играй в оконном без рамок либо в оконном, можешь закрывать issue

**Comment by hafizov444** [comment]
> > > после установки этой хуйни, перезагрузись, а вообще лучше переустанови pip install --upgrade numpy
> > 
> > 
> > Так, одно пофиксил, теперь второе вылезло Запускал в оконном, в фулл не работает ![sPtvdAYfG1w](https://private-user-images.githubusercontent.com/153525168/289604967-83a41436-c869-490f-9187-e979254613f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTMwNTUsIm5iZiI6MTcwMjMxMjc1NSwicGF0aCI6Ii8xNTM1MjUxNjgvMjg5NjA0OTY3LTgzYTQxNDM2LWM4NjktNDkwZi05MTg3LWU5NzkyNTQ2MTNmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNjM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmMwYTg5MzYzYjA5NzIyYjFkODg5ZGU5MzU4MDNmYzhiYTc3NzM3Njc4NWJmMzJjZTdkYTBhZTlhZDJhZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DEYVl_zIi1jk2XeEhDXV5Udd_NzjLzFtj4t-udDXVwA)
> 
> так тебе это фиксить не надо? поддержки полного экрана нету, играй в оконном без рамок либо в оконном, можешь закрывать issue

Проблема в том, то что нет никакого отображения, и на таргеты никак не реагирует

**Comment by cats-ui** [comment]
> > > > после установки этой хуйни, перезагрузись, а вообще лучше переустанови pip install --upgrade numpy
> > > 
> > > 
> > > Так, одно пофиксил, теперь второе вылезло Запускал в оконном, в фулл не работает ![sPtvdAYfG1w](https://private-user-images.githubusercontent.com/153525168/289604967-83a41436-c869-490f-9187-e979254613f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTMwNTUsIm5iZiI6MTcwMjMxMjc1NSwicGF0aCI6Ii8xNTM1MjUxNjgvMjg5NjA0OTY3LTgzYTQxNDM2LWM4NjktNDkwZi05MTg3LWU5NzkyNTQ2MTNmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNjM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmMwYTg5MzYzYjA5NzIyYjFkODg5ZGU5MzU4MDNmYzhiYTc3NzM3Njc4NWJmMzJjZTdkYTBhZTlhZDJhZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DEYVl_zIi1jk2XeEhDXV5Udd_NzjLzFtj4t-udDXVwA)
> > 
> > 
> > так тебе это фиксить не надо? поддержки полного экрана нету, играй в оконном без рамок либо в оконном, можешь закрывать issue
> 
> Проблема в том, то что нет никакого отображения, и на таргеты никак не реагирует

установи cudnn, в questions файле разраб заливал вроде, хуй знает, вообщем если полистаешь иссуес я кидал уже сто раз, и почему ты вообще .pt модель юзаешь?

**Comment by hafizov444** [comment]
> > > > > после установки этой хуйни, перезагрузись, а вообще лучше переустанови pip install --upgrade numpy
> > > > 
> > > > 
> > > > Так, одно пофиксил, теперь второе вылезло Запускал в оконном, в фулл не работает ![sPtvdAYfG1w](https://private-user-images.githubusercontent.com/153525168/289604967-83a41436-c869-490f-9187-e979254613f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTMwNTUsIm5iZiI6MTcwMjMxMjc1NSwicGF0aCI6Ii8xNTM1MjUxNjgvMjg5NjA0OTY3LTgzYTQxNDM2LWM4NjktNDkwZi05MTg3LWU5NzkyNTQ2MTNmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNjM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmMwYTg5MzYzYjA5NzIyYjFkODg5ZGU5MzU4MDNmYzhiYTc3NzM3Njc4NWJmMzJjZTdkYTBhZTlhZDJhZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DEYVl_zIi1jk2XeEhDXV5Udd_NzjLzFtj4t-udDXVwA)
> > > 
> > > 
> > > так тебе это фиксить не надо? поддержки полного экрана нету, играй в оконном без рамок либо в оконном, можешь закрывать issue
> > 
> > 
> > Проблема в том, то что нет никакого отображения, и на таргеты никак не реагирует
> 
> установи cudnn, в questions файле разраб заливал вроде, хуй знает, вообщем если полистаешь иссуес я кидал уже сто раз, и почему ты вообще .pt модель юзаешь?

cudnn устанавливал, что юзать я не шарю, делаю как по гайду

**Comment by cats-ui** [comment]
> > > > > > после установки этой хуйни, перезагрузись, а вообще лучше переустанови pip install --upgrade numpy
> > > > > 
> > > > > 
> > > > > Так, одно пофиксил, теперь второе вылезло Запускал в оконном, в фулл не работает ![sPtvdAYfG1w](https://private-user-images.githubusercontent.com/153525168/289604967-83a41436-c869-490f-9187-e979254613f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTMwNTUsIm5iZiI6MTcwMjMxMjc1NSwicGF0aCI6Ii8xNTM1MjUxNjgvMjg5NjA0OTY3LTgzYTQxNDM2LWM4NjktNDkwZi05MTg3LWU5NzkyNTQ2MTNmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNjM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmMwYTg5MzYzYjA5NzIyYjFkODg5ZGU5MzU4MDNmYzhiYTc3NzM3Njc4NWJmMzJjZTdkYTBhZTlhZDJhZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DEYVl_zIi1jk2XeEhDXV5Udd_NzjLzFtj4t-udDXVwA)
> > > > 
> > > > 
> > > > так тебе это фиксить не надо? поддержки полного экрана нету, играй в оконном без рамок либо в оконном, можешь закрывать issue
> > > 
> > > 
> > > Проблема в том, то что нет никакого отображения, и на таргеты никак не реагирует
> > 
> > 
> > установи cudnn, в questions файле разраб заливал вроде, хуй знает, вообщем если полистаешь иссуес я кидал уже сто раз, и почему ты вообще .pt модель юзаешь?
> 
> cudnn устанавливал, что юзать я не шарю, делаю как по гайду

скинь options py

**Comment by hafizov444** [comment]
> > > > > > > после установки этой хуйни, перезагрузись, а вообще лучше переустанови pip install --upgrade numpy
> > > > > > 
> > > > > > 
> > > > > > Так, одно пофиксил, теперь второе вылезло Запускал в оконном, в фулл не работает ![sPtvdAYfG1w](https://private-user-images.githubusercontent.com/153525168/289604967-83a41436-c869-490f-9187-e979254613f8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTMwNTUsIm5iZiI6MTcwMjMxMjc1NSwicGF0aCI6Ii8xNTM1MjUxNjgvMjg5NjA0OTY3LTgzYTQxNDM2LWM4NjktNDkwZi05MTg3LWU5NzkyNTQ2MTNmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNjM5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmMwYTg5MzYzYjA5NzIyYjFkODg5ZGU5MzU4MDNmYzhiYTc3NzM3Njc4NWJmMzJjZTdkYTBhZTlhZDJhZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DEYVl_zIi1jk2XeEhDXV5Udd_NzjLzFtj4t-udDXVwA)
> > > > > 
> > > > > 
> > > > > так тебе это фиксить не надо? поддержки полного экрана нету, играй в оконном без рамок либо в оконном, можешь закрывать issue
> > > > 
> > > > 
> > > > Проблема в том, то что нет никакого отображения, и на таргеты никак не реагирует
> > > 
> > > 
> > > установи cudnn, в questions файле разраб заливал вроде, хуй знает, вообщем если полистаешь иссуес я кидал уже сто раз, и почему ты вообще .pt модель юзаешь?
> > 
> > 
> > cudnn устанавливал, что юзать я не шарю, делаю как по гайду
> 
> скинь options py

У меня нет options

**Comment by cats-ui** [comment]
блять почему ты такой трудный, ну конфиг какая разница

**Comment by hafizov444** [comment]
> блять почему ты такой трудный, ну конфиг какая разница

Не ругайся((
[1.zip](https://github.com/SunOner/yolov8_aimbot/files/13638768/1.zip)

**Comment by cats-ui** [comment]
> > блять почему ты такой трудный, ну конфиг какая разница
> 
> Не ругайся(( [1.zip](https://github.com/SunOner/yolov8_aimbot/files/13638768/1.zip)

нахуя ты зипом скинул???? просто отправь текстом

**Comment by hafizov444** [comment]
> > > блять почему ты такой трудный, ну конфиг какая разница
> > 
> > 
> > Не ругайся(( [1.zip](https://github.com/SunOner/yolov8_aimbot/files/13638768/1.zip)
> 
> нахуя ты зипом скинул???? просто отправь текстом

[Detection window]
detection_window_width = 384
detection_window_height = 216 

[Dxcam Capture]
Dxcam_capture = yes
dxcam_capture_fps = 30
dxcam_monitor_id = 0
dxcam_gpu_id = 0
dxcam_max_buffer_len = 64

[Obs capture]
Obs_capture = no
Obs_camera_id = 1
Obs_capture_fps = 30

[Windows capture]
native_Windows_capture = no

[Aim settings]
body_y_offset = 0.35
hideout_targets = no
disable_headshot = no

[Mouse settings]
mouse_break_force = 0
mouse_smoothing = 1
mouse_auto_shoot = no
mouse_auto_aim = no
mouse_native = yes
mouse_wild_mouse = yes

[AI options]
# You can find new improved models here https://boosty.to/sunone
AI_model_path = sunxds_0.2.1_nano_320.pt
AI_image_size = 320
AI_conf = 0.35
AI_iou = 0.1
AI_device = 0
AI_max_det = 10

[Debug window]
show_window = no
show_speed = no
show_fps = no
show_boxes = yes
show_labels = yes
show_conf = yes
debug_window_scale_percent = 100
debug_window_name = 'Calculator'

**Comment by cats-ui** [comment]
почему ты юзаешь pt модель вместо engine?

**Comment by hafizov444** [comment]
> почему ты юзаешь pt модель вместо engine?

Я не знаю как юзать engine мужик, говорю же делал все по гайду
