### ISSUE TITLE
Export not working...

### ISSUE THREAD

**Issue by RobinsKonto8** [SunOner/yolov8_aimbot#87]
I followed the EN installation guide and the aimbot works, but in the final step to export, it doesn't work. Nothing happens (see image).

command: 
yolo export model="models\sunxds_0.2.1_nano_320.pt" format=engine half=true device=0 workspace=4 imgsz=320

![Fehler](https://github.com/SunOner/yolov8_aimbot/assets/130449780/096006a3-c768-4bf8-a145-e5c1f9e3e784)

**Comment by lukeg87** [comment]
`pip uninstall onnx`

run export again, there is a bug, you need to remove onnx everytime before export 🤷

**Comment by RobinsKonto8** [comment]
@SunOner I have now the same Error as a prior issue: "NoneType' object does not support the context manager protocol".

Is there a solution to this?

**Comment by cats-ui** [comment]
> @SunOner I have now the same Error as a prior issue: "NoneType' object does not support the context manager protocol".
> 
> Is there a solution to this?

send cmd screenshot i dont know what u talking about

**Comment by RobinsKonto8** [comment]
![Fehler](https://github.com/SunOner/yolov8_aimbot/assets/130449780/ab3cd999-d462-4484-972d-a42e32c41ffc)

**Comment by cats-ui** [comment]
> ![Fehler](https://private-user-images.githubusercontent.com/130449780/289579345-ab3cd999-d462-4484-972d-a42e32c41ffc.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTMxMTcsIm5iZiI6MTcwMjMxMjgxNywicGF0aCI6Ii8xMzA0NDk3ODAvMjg5NTc5MzQ1LWFiM2NkOTk5LWQ0NjItNDQ4NC05NzJkLWE0MmUzMmM0MWZmYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNjQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTgwY2QwODRjYWYyZjMzODhkZGI5ZjA1ZTVlMGM4YTNmYjI5NzkzN2NhNzRhNmNkNTBjM2Q3YTRmZjU5N2QwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0E3_3WKIDXSFXsZLPYgdTCxu3EmUgyaeb-BOWD-Kds8)

whats ur gpu?

**Comment by cats-ui** [comment]
i think there’s currently no fix for that issue 
even google says nothing idk actually

**Comment by Kirillh993** [comment]
> ![Фелер](https://private-user-images.githubusercontent.com/130449780/289579345-ab3cd999-d462-4484-972d-a42e32c41ffc.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTczNjcsIm5iZiI6MTcwMjMxNzA2NywicGF0aCI6Ii8xMzA0NDk3ODAvMjg5NTc5MzQ1LWFiM2NkOTk5LWQ0NjItNDQ4NC05NzJkLWE0MmUzMmM0MWZmYy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNzUxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTNiNGI3MjE4N2IwODg1NGVmOWVkY2Y4NWI1NjQwYzc1NTE4ZDYyYmJlMGJhMzIxMzU5M2MyOGJiYjEyNGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YLnA1gKC80sFF2eBG4Os3yGoukLe0oSJDNPM1EefWxw)

ТАКАЯ ЖЕ БЕДА У МЕНЯ МУЖИК

**Comment by cats-ui** [comment]
> @SunOner I have a GTX 970. I think this is the problem. I have to get a new GPU. Thanks for your help. Can you as a last question recommend a graphic card for AIs like this?
> 
> Would a RTX 4060 be enough to run this program smoothly in the future? :) Thanks

yes but rtx 4060 ti would be so much better man
