### ISSUE TITLE
не работает кнопка, хотя ии видит 

### ISSUE THREAD

**Issue by inuokaaa** [SunOner/yolov8_aimbot#88]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/16b98d0a-7e1a-4f5c-923c-ae828e5f7a2e)
не наводится, хотя всё видит, кнопки уже менял

**Comment by inuokaaa** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153482514/f81769bd-f99a-44d9-9903-38fabc04f912)
мб с настройками чёт не так

**Comment by cats-ui** [comment]
АХХАХААХАХХАХХААХ ТЫ НАВЕРН САМЫЙ ТУПОЙ

**Comment by cats-ui** [comment]
это все мрак тебе запрещает с читами играть

**Comment by cats-ui** [comment]
https://github.com/SunOner/yolov8_aimbot/issues/92

**Comment by cats-ui** [comment]
мрак теб удалил акк на гите

**Comment by JayaLZT** [comment]
> ![image](https://private-user-images.githubusercontent.com/153482514/289596040-f81769bd-f99a-44d9-9903-38fabc04f912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MjUwNjMsIm5iZiI6MTcxMDYyNDc2MywicGF0aCI6Ii8xNTM0ODI1MTQvMjg5NTk2MDQwLWY4MTc2OWJkLWY5OWEtNDRkOS05OTAzLTM4ZmFiYzA0ZjkxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQyMTMyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjBjNDE1NDZjZWMwOWI1NDE4NDhhZTBmNzVlOWZiZGQ5OGNhNDgxOTljYWRmODVhMGYyYWM2N2Q4NGNhNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6HTZGrCb4M603QdAshr-qFSl0yUXRqgg-JMRHi_HoD0) мб с настройками чёт не так

как решил?
