### ISSUE TITLE
Мгновенно закрывается CMD после запуска

### ISSUE THREAD

**Issue by IdyNaLan** [SunOner/yolov8_aimbot#94]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153688473/e2021c0c-9610-41e4-8083-880e8bfb8542)

Запускаю бота и он сразу выключается. Без ардуино не работает? устанавливал все по инструкции

**Comment by cats-ui** [comment]
выключи ардуино в настройках блять

**Comment by IdyNaLan** [comment]
> выключи ардуино в настройках блять

выключена итак
[Detection window]
detection_window_width = 384
detection_window_height = 216 

[Dxcam Capture]
Dxcam_capture = yes
dxcam_capture_fps = 30
dxcam_monitor_id = 0
dxcam_gpu_id = 0
dxcam_max_buffer_len = 64

[Obs capture]
Obs_capture = no
Obs_camera_id = 1
Obs_capture_fps = 30

[Windows capture]
native_Windows_capture = no

[Aim settings]
body_y_offset = 0.35
hideout_targets = no
disable_headshot = no

[Mouse settings]
mouse_break_force = 0
mouse_smoothing = 1
mouse_auto_shoot = no
mouse_auto_aim = yes
mouse_native = no
mouse_wild_mouse = no
mouse_move_by_arduino = no
mouse_shoot_by_arduino = no

[AI options]
# You can find new improved models here https://boosty.to/sunone
AI_model_path = sunxds_0.2.1_nano_320.pt
AI_image_size = 320
AI_conf = 0.35
AI_iou = 0.1
AI_device = 0
AI_max_det = 10

[Debug window]
show_window = true
show_speed = no
show_fps = no
show_boxes = yes
show_labels = yes
show_conf = yes
debug_window_scale_percent = 100
debug_window_name = 'Calculator'

**Comment by cats-ui** [comment]
> > выключи ардуино в настройках блять
> 
> выключена итак [Detection window] detection_window_width = 384 detection_window_height = 216
> 
> [Dxcam Capture] Dxcam_capture = yes dxcam_capture_fps = 30 dxcam_monitor_id = 0 dxcam_gpu_id = 0 dxcam_max_buffer_len = 64
> 
> [Obs capture] Obs_capture = no Obs_camera_id = 1 Obs_capture_fps = 30
> 
> [Windows capture] native_Windows_capture = no
> 
> [Aim settings] body_y_offset = 0.35 hideout_targets = no disable_headshot = no
> 
> [Mouse settings] mouse_break_force = 0 mouse_smoothing = 1 mouse_auto_shoot = no mouse_auto_aim = yes mouse_native = no mouse_wild_mouse = no mouse_move_by_arduino = no mouse_shoot_by_arduino = no
> 
> [AI options]
> 
> # You can find new improved models here https://boosty.to/sunone
> AI_model_path = sunxds_0.2.1_nano_320.pt AI_image_size = 320 AI_conf = 0.35 AI_iou = 0.1 AI_device = 0 AI_max_det = 10
> 
> [Debug window] show_window = true show_speed = no show_fps = no show_boxes = yes show_labels = yes show_conf = yes debug_window_scale_percent = 100 debug_window_name = 'Calculator'

пофиксили, обнови

**Comment by IdyNaLan** [comment]
![image](https://github.com/SunOner/yolov8_aimbot/assets/153688473/b8f10a75-e826-44a0-947d-8417d1c2f738)
Все так же моментально выкидывает

**Comment by SunOner** [comment]
Попробуй обновить
