### ISSUE TITLE
Automatic adsorption problem

### ISSUE THREAD

**Issue by 2662007798** [SunOner/yolov8_aimbot#95]
In the process of use, adjust the config.ini file to set mouse_break_force and mouse_smoothing to correct the mouse, but in the adsorption process, if the star is far away from the character, it will quickly adsorb, but the distance is too close, the adsorption speed is very slow. 
Is it the algorithm?

**Comment by cats-ui** [comment]
hey, the algorithm might calculate the adsorption force based on both distance and mouse movement. if your adjustments to mouse_break_force and mouse_smoothing affect the mouse movement behavior,  it might indirectly affect the calculated force, causing the speed differences you’re seeing. Also it’s a good idea to propose a customization option for parameters like "adsorption_threshold" or "adsorption_force_curve" to the dev. this  could really enhance user control and address specific issues more easily

**Comment by 2662007798** [comment]
yes,bro   I noticed that there will be some problems in a method, and I'm going to try to modify it later, and I'll share it if I can.

**Comment by 2662007798** [comment]
> hey, the algorithm might calculate the adsorption force based on both distance and mouse movement. if your adjustments to mouse_break_force and mouse_smoothing affect the mouse movement behavior, it might indirectly affect the calculated force, causing the speed differences you’re seeing. Also it’s a good idea to propose a customization option for parameters like "adsorption_threshold" or "adsorption_force_curve" to the dev. this could really enhance user control and address specific issues more easily

yes,bro I noticed that there will be some problems in a method, and I'm going to try to modify it later, and I'll share it if I can.

**Comment by cats-ui** [comment]
close
