### ISSUE TITLE
How do I make aimbot work on the left mouse button and not the right one?

### ISSUE THREAD

**Issue by TiringaMente** [SunOner/yolov8_aimbot#98]
How do I make aimbot work on the left mouse button and not the right one?

**Comment by cats-ui** [comment]
поменяй в коде правую кнопку мыши на левую

**Comment by TiringaMente** [comment]
in which file? It is like?

**Comment by TiringaMente** [comment]
the ideal would be to activate and pause on f2

**Comment by cats-ui** [comment]
> in which file? It is like?

run.py

**Comment by TiringaMente** [comment]
Thanks, I managed to shift the aimbot to the left, how do I just pause on F2 and return without closing

**Comment by TiringaMente** [comment]
The only thing I can't do is make it work in the Black Squad game, why? 
https://store.steampowered.com/app/550650/Black_Squad/

**Comment by cats-ui** [comment]
close issue nigga
